//
// This is a file generated by DDR wizard.
// Please do not edit this file!
// Generated time: 09/03/2019 11:26:44
// Version: Fuxi 2019.1 win64
// Wizard name: DDR 1.0a
//
// ============================================================
// File Name: ddr_v1.v
// IP core : ddr
// Device name: C1P060TF784C7-ES
// ============================================================

module ddr_v1(
    I_mc_rstn,
    I_mc_pclk,
    I_cfg_rstn,
    I_cfg_pclk,
    O_init_done,
    O_init_pass,
    O_error_status,
    O_error_status_en,
    I_pbus_aclk0,
    axi_port00_arid,
    axi_port00_araddr,
    axi_port00_arlen,
    axi_port00_arsize,
    axi_port00_arburst,
    axi_port00_arvalid,
    axi_port00_arready,
    axi_port00_rid,
    axi_port00_rdata,
    axi_port00_rresp,
    axi_port00_rlast,
    axi_port00_rvalid,
    axi_port00_rready,
    axi_port00_awid,
    axi_port00_awaddr,
    axi_port00_awlen,
    axi_port00_awsize,
    axi_port00_awburst,
    axi_port00_awvalid,
    axi_port00_awready,
    axi_port00_wid,
    axi_port00_wdata,
    axi_port00_wstrb,
    axi_port00_wlast,
    axi_port00_wvalid,
    axi_port00_wready,
    axi_port00_bid,
    axi_port00_bresp,
    axi_port00_bvalid,
    axi_port00_bready,
    I_pbus_aclk1,
    axi_port01_arid,
    axi_port01_araddr,
    axi_port01_arlen,
    axi_port01_arsize,
    axi_port01_arburst,
    axi_port01_arvalid,
    axi_port01_arready,
    axi_port01_rid,
    axi_port01_rdata,
    axi_port01_rresp,
    axi_port01_rlast,
    axi_port01_rvalid,
    axi_port01_rready,
    axi_port01_awid,
    axi_port01_awaddr,
    axi_port01_awlen,
    axi_port01_awsize,
    axi_port01_awburst,
    axi_port01_awvalid,
    axi_port01_awready,
    axi_port01_wid,
    axi_port01_wdata,
    axi_port01_wstrb,
    axi_port01_wlast,
    axi_port01_wvalid,
    axi_port01_wready,
    axi_port01_bid,
    axi_port01_bresp,
    axi_port01_bvalid,
    axi_port01_bready
);

input I_mc_rstn;
input I_mc_pclk;
input I_cfg_rstn;
input I_cfg_pclk;
output O_init_done;
output O_init_pass;
output [2:0] O_error_status;
output O_error_status_en;
input I_pbus_aclk0;
input [15:0] axi_port00_arid;
input [31:0] axi_port00_araddr;
input [3:0] axi_port00_arlen;
input [2:0] axi_port00_arsize;
input [1:0] axi_port00_arburst;
input axi_port00_arvalid;
output axi_port00_arready;
output [15:0] axi_port00_rid;
output [127:0] axi_port00_rdata;
output [1:0] axi_port00_rresp;
output axi_port00_rlast;
output axi_port00_rvalid;
input axi_port00_rready;
input [15:0] axi_port00_awid;
input [31:0] axi_port00_awaddr;
input [3:0] axi_port00_awlen;
input [2:0] axi_port00_awsize;
input [1:0] axi_port00_awburst;
input axi_port00_awvalid;
output axi_port00_awready;
input [15:0] axi_port00_wid;
input [127:0] axi_port00_wdata;
input [15:0] axi_port00_wstrb;
input axi_port00_wlast;
input axi_port00_wvalid;
output axi_port00_wready;
output [15:0] axi_port00_bid;
output [1:0] axi_port00_bresp;
output axi_port00_bvalid;
input axi_port00_bready;
input I_pbus_aclk1;
input [15:0] axi_port01_arid;
input [31:0] axi_port01_araddr;
input [3:0] axi_port01_arlen;
input [2:0] axi_port01_arsize;
input [1:0] axi_port01_arburst;
input axi_port01_arvalid;
output axi_port01_arready;
output [15:0] axi_port01_rid;
output [127:0] axi_port01_rdata;
output [1:0] axi_port01_rresp;
output axi_port01_rlast;
output axi_port01_rvalid;
input axi_port01_rready;
input [15:0] axi_port01_awid;
input [31:0] axi_port01_awaddr;
input [3:0] axi_port01_awlen;
input [2:0] axi_port01_awsize;
input [1:0] axi_port01_awburst;
input axi_port01_awvalid;
output axi_port01_awready;
input [15:0] axi_port01_wid;
input [127:0] axi_port01_wdata;
input [15:0] axi_port01_wstrb;
input axi_port01_wlast;
input axi_port01_wvalid;
output axi_port01_wready;
output [15:0] axi_port01_bid;
output [1:0] axi_port01_bresp;
output axi_port01_bvalid;
input axi_port01_bready;

cme_ddr_core_top_v1 #(
        .CFG_MC_BUS_SEL (1'h0),		// set 4120_8000_bit[0].. 1:sdii, 0: axi.
        .CFG_IP2IP_SEL  (1'h0),		// set 4170_011C_bit[0].. 1=gx/ddr bus inferface connect to array ; 0= gx/ddr bus inferface connect to spine.
		
        .reg32_50  (32'h00000000),  //LSB：1：axi00 disable
		.reg32_104 (32'h00100851),	//bit25=1：Controller training mode   bit25=0：PHY training mode 20200703  bit20：Clone Enable
		.reg32_108 (32'h0186a000),  //Timer for PVT auto-calibration: 128 ms for MC_CLK = 200Mhz
		.reg32_10c (32'h55e00a0a),
        .reg32_110 (32'h00000000),	//for P1 device dll phase; bit29=1: >800Mbps, =0 :<=800Mbps; other bits shall be 0
		.reg32_114 (32'h000a0200),	//x16 reduce mode, bit 17/19: 11-disable DQ8-15/24-31;  0200: enable ddr phy training manual mode 20200703

		//.reg32_140 (32'h86000000),	//PVT auto-calibration mode enable	
		//.reg32_144 (32'h00108600),
		
		.reg32_148 (32'h80000000),
		
		//.reg32_190 (32'h00100008), //MLB train Setting..
		
        .reg32_04 (32'h00258000),
        .reg32_08 (32'h08080c30),
		
        .reg32_28 (32'h00000018),
        .reg32_2c (32'h1d700042),
		
        .reg32_0c (32'hfffff124),  //DFI  
        .reg32_10 (32'h02030305),  //tRTW=?, tWTR=6, tRRD=6,tCCD=4
        .reg32_14 (32'h03064010),  //tFAW=40,tRFC=280, tWR=15,tRTP=6
        .reg32_18 (32'h06060e06),  //tRCD=11(13.75ns),tRAS=30(37.5ns),tRP=12(15ns)
        .reg32_1c (32'h40040006),  //CL=11,AL=0,CWL=5,ODT delay =0
		
        .reg32_20 (32'h01000044),
        .reg32_24 (32'h00030602),  //tMRD=4,tMOD=12,r_zqcs_limit=3
        .reg32_30 (32'h01000404),  //tCKSRE=8,tCKSRX=8,tXSDLL=0200
        .reg32_34 (32'h020a0344),  //tXS=44,tXP=04,tXPDLL=20,tCKE=04
        .reg32_38 (32'h00060c08),  //tRDPDEN=16,tWRPDEN=21,t_pd_timer_limit=0006
		//.reg32_3c (32'h00010981),  //1:Training/4:CPUIF;2Gb x16 DRAM：32'h00010981
		.reg32_3c (32'h00010d01),  //1:Training/4:CPUIF;1Gb x16 DRAM：32'h00010d01
		
		.reg32_54 (32'h04000000),  //x16 reduce mode, bit 26: 0-full DQ mode,DQ 0-31;1-half DQ mode DQ0-15
        .reg32_58 (32'h00000000),
		
		.reg32_00 (32'h00000001)	//Enable controller	
)
u_inst (
        .I_mc_rstn (I_mc_rstn),
        .I_mc_pclk (I_mc_pclk),
        .I_cfg_rstn (I_cfg_rstn),
        .I_cfg_pclk (I_cfg_pclk),
        .O_init_done (O_init_done),
        .O_init_pass (O_init_pass),
        .O_error_status (O_error_status),
        .O_error_status_en (O_error_status_en),
        .I_pbus_aclk0 (I_pbus_aclk0),
        .axi_port00_arid (axi_port00_arid),
        .axi_port00_araddr (axi_port00_araddr),
        .axi_port00_arlen (axi_port00_arlen),
        .axi_port00_arsize (axi_port00_arsize),
        .axi_port00_arburst (axi_port00_arburst),
        .axi_port00_arvalid (axi_port00_arvalid),
        .axi_port00_arready (axi_port00_arready),
        .axi_port00_rid (axi_port00_rid),
        .axi_port00_rdata (axi_port00_rdata),
        .axi_port00_rresp (axi_port00_rresp),
        .axi_port00_rlast (axi_port00_rlast),
        .axi_port00_rvalid (axi_port00_rvalid),
        .axi_port00_rready (axi_port00_rready),
        .axi_port00_awid (axi_port00_awid),
        .axi_port00_awaddr (axi_port00_awaddr),
        .axi_port00_awlen (axi_port00_awlen),
        .axi_port00_awsize (axi_port00_awsize),
        .axi_port00_awburst (axi_port00_awburst),
        .axi_port00_awvalid (axi_port00_awvalid),
        .axi_port00_awready (axi_port00_awready),
        .axi_port00_wid (axi_port00_wid),
        .axi_port00_wdata (axi_port00_wdata),
        .axi_port00_wstrb (axi_port00_wstrb),
        .axi_port00_wlast (axi_port00_wlast),
        .axi_port00_wvalid (axi_port00_wvalid),
        .axi_port00_wready (axi_port00_wready),
        .axi_port00_bid (axi_port00_bid),
        .axi_port00_bresp (axi_port00_bresp),
        .axi_port00_bvalid (axi_port00_bvalid),
        .axi_port00_bready (axi_port00_bready),
        .axi_port01_arid (axi_port01_arid),
        .I_pbus_aclk1 (I_pbus_aclk1),
        .axi_port01_araddr (axi_port01_araddr),
        .axi_port01_arlen (axi_port01_arlen),
        .axi_port01_arsize (axi_port01_arsize),
        .axi_port01_arburst (axi_port01_arburst),
        .axi_port01_arvalid (axi_port01_arvalid),
        .axi_port01_arready (axi_port01_arready),
        .axi_port01_rid (axi_port01_rid),
        .axi_port01_rdata (axi_port01_rdata),
        .axi_port01_rresp (axi_port01_rresp),
        .axi_port01_rlast (axi_port01_rlast),
        .axi_port01_rvalid (axi_port01_rvalid),
        .axi_port01_rready (axi_port01_rready),
        .axi_port01_awid (axi_port01_awid),
        .axi_port01_awaddr (axi_port01_awaddr),
        .axi_port01_awlen (axi_port01_awlen),
        .axi_port01_awsize (axi_port01_awsize),
        .axi_port01_awburst (axi_port01_awburst),
        .axi_port01_awvalid (axi_port01_awvalid),
        .axi_port01_awready (axi_port01_awready),
        .axi_port01_wid (axi_port01_wid),
        .axi_port01_wdata (axi_port01_wdata),
        .axi_port01_wstrb (axi_port01_wstrb),
        .axi_port01_wlast (axi_port01_wlast),
        .axi_port01_wvalid (axi_port01_wvalid),
        .axi_port01_wready (axi_port01_wready),
        .axi_port01_bid (axi_port01_bid),
        .axi_port01_bresp (axi_port01_bresp),
        .axi_port01_bvalid (axi_port01_bvalid),
        .axi_port01_bready (axi_port01_bready)
);

endmodule

// ============================================================
//                  ddr Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : C1P060TF784C7-ES
// Module          : ddr_v1
// IP core         : ddr
// IP Version      : 1

// BusType         : AXI
// DDRMode         : DDR3
// DataRate        : 800
// EccEnabled      : false
// Simulation Files: ../ip_core/ddr_v1/
// Synthesis Files : src/ccb_ddr_cfg_top.v src/check_ddr_cfg_done.v src/array2ddr_mux.v
