//
// This is a file generated by Debugware wizard.
// Please do not edit this file!
// Generated time: 01/03/2020 16:10:35
// Version: Fuxi fuxi win64
// Wizard name: Debugware 2.1a
//
// ============================================================
// File Name: debugware_v2_1.v
// IP core : debugware
// Device name: C1P060TF784C7-ES
// ============================================================

module debugware_v2_1(
    trig_out_0,
    data_in_0,
    ref_clk_0,
    trig_out_1,
    data_in_1,
    ref_clk_1
);

output trig_out_0;
input [135:0] data_in_0;
input ref_clk_0;
output trig_out_1;
input [155:0] data_in_1;
input ref_clk_1;

wire tck1, tdi1, tdo1, sel1, tck2, tdi2, tdo2, sel2, update, shift, reset;
wire [1:0] la_sel;
wire [1:0] la_tdo;
wire status, ctrl, offset, mem, la_reset, la_tck, la_tdi, la_shift, la_update;
tap #( .DEVICE_NAME (4) ) u_tap (
        .tck1 (tck1),
        .tdi1 (tdi1),
        .tdo1 (tdo1),
        .sel1 (sel1),
        .tck2 (tck2),
        .tdi2 (tdi2),
        .tdo2 (tdo2),
        .sel2 (sel2),
        .update (update),
        .shift (shift),
        .reset (reset)
);
wire update_clk;
GBUF u_gbuf_update (
        .in (update),
        .out (update_clk)
);
la_manager #( .NUM_OF_LA (2) ) u_la_manager (
        .tck1 (tck1),
        .tdi1 (tdi1),
        .tdo1 (tdo1),
        .sel1 (sel1),
        .tck2 (tck2),
        .tdi2 (tdi2),
        .tdo2 (tdo2),
        .sel2 (sel2),
        .update (update),
        .update_clk (update_clk),
        .shift (shift),
        .reset (reset),
        .la_sel (la_sel),
        .status (status),
        .ctrl (ctrl),
        .mem (mem),
        .offset (offset),
        .la_reset (la_reset),
        .la_tck (la_tck),
        .la_update (la_update),
        .la_shift (la_shift),
        .la_tdi (la_tdi),
        .la_tdo (la_tdo)
);
la_core #(
        .DATA_WIDTH (136),
        .SAMPLE_DEPTH (512),
        .ADDR_WIDTH (9),
        .DEVICE_NAME (4)
)
u_la_core_0 (
        .sel (la_sel[0]),
        .status_sel (status),
        .ctrl_sel (ctrl),
        .mem_sel (mem),
        .offset_sel (offset),
        .reset (la_reset&la_sel[0]),
        .tck (la_tck),
        .update (la_update),
        .shift (la_shift),
        .tdi (la_tdi),
        .tdo (la_tdo[0]),
        .trig_out (trig_out_0),
        .data_in (data_in_0),
        .ref_clk (ref_clk_0),
        .reset_raddr (update&mem&sel1),
        .mem_read (update_clk)
);
la_core #(
        .DATA_WIDTH (156),
        .SAMPLE_DEPTH (512),
        .ADDR_WIDTH (9),
        .DEVICE_NAME (4)
)
u_la_core_1 (
        .sel (la_sel[1]),
        .status_sel (status),
        .ctrl_sel (ctrl),
        .mem_sel (mem),
        .offset_sel (offset),
        .reset (la_reset&la_sel[1]),
        .tck (la_tck),
        .update (la_update),
        .shift (la_shift),
        .tdi (la_tdi),
        .tdo (la_tdo[1]),
        .trig_out (trig_out_1),
        .data_in (data_in_1),
        .ref_clk (ref_clk_1),
        .reset_raddr (update&mem&sel1),
        .mem_read (update_clk)
);

endmodule

// ============================================================
//                  debugware Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : C1P060TF784C7-ES
// Module          : debugware_v2_1
// IP core         : debugware
// IP Version      : 2_1

// LA0_StorageDepth: 9
// LA0_StorageWidth: 136
// LA1_StorageDepth: 9
// LA1_StorageWidth: 156
// LaCoreCount     : 2
// Simulation Files: 
// Synthesis Files : src/dwip.v
