//
// This is a file generated by FIFO wizard.
// Please do not edit this file!
// Generated time: 06/22/2022 15:05:15
// Version: Fuxi fx2020a win64
// Wizard name: FIFO 2.0a
//
// ============================================================
// File Name: fifo2ddr.v
// IP core : fifo
// Device name: P1P060N0V324C7
// ============================================================

module fifo2ddr(
    clk,
    rst_n,
    wdata,
    rdata,
    wen,
    ren,
    wr_data_cnt,
    rd_data_cnt,
    rempty,
    wfull
);

input clk;
input rst_n;
input [63:0] wdata;
output [127:0] rdata;
input wen;
input ren;
output [6:0] wr_data_cnt;
output [5:0] rd_data_cnt;
output rempty;
output wfull;

wire clkw;
assign clkw = clk;
wire clkr;
assign clkr = clk;
wire cew;
wire cer;
wire [5:0] ar;
wire [6:0] aw;
wire [63:0] dw;
wire [127:0] qr;

fifo2ddr_emb_v1 u_inst (
        .ar (ar),
        .aw (aw),
        .clkr (clkr),
        .clkw (clkw),
        .cer (cer),
        .cew (cew),
        .dw (dw),
        .qr (qr),
        .rstnr (rst_n)
);

cme_ip_syn_fifo_v2 #(
        .wr_dw (64),
        .rd_dw (128),
        .wr_aw (7),
        .rd_aw (6),
        .wr_depth (128),
        .rd_depth (64),
        .fwft_en (1'b1),
        .tDLY (0),
        .gen_prog_full_type (3'b000),
        .gen_prog_empty_type (3'b000),
        .prog_full_const (60),
        .prog_empty_const (30),
        .prog_full_assert_const (60),
        .prog_full_negate_const (58),
        .prog_empty_assert_const (30),
        .prog_empty_negate_const (29),
        .gen_almost_full (1'b0),
        .gen_almost_empty (1'b0),
        .gen_prog_full (1'b0),
        .gen_prog_empty (1'b0),
        .gen_wr_data_cnt (1'b1),
        .gen_rd_data_cnt (1'b1),
        .gen_wr_ack (1'b0),
        .gen_rd_ack (1'b0),
        .gen_wr_overflow (1'b0),
        .gen_rd_underflow (1'b0),
        .need_syn_wr_clr (1'b0),
        .need_syn_rd_clr (1'b0)
)
u_syn_fifo (
        .clk (clk),
        .rst_n (rst_n),
        .wclr (),
        .rclr (),
        .wdata (wdata),
        .rdata (rdata),
        .wen (wen),
        .ren (ren),
        .almost_full (),
        .almost_empty (),
        .prog_full (),
        .prog_empty (),
        .wr_data_cnt (wr_data_cnt),
        .rd_data_cnt (rd_data_cnt),
        .rempty (rempty),
        .wfull (wfull),
        .prog_full_thresh (),
        .prog_empty_thresh (),
        .prog_full_assert (),
        .prog_full_negate (),
        .prog_empty_assert (),
        .prog_empty_negate (),
        .wr_ack (),
        .rd_ack (),
        .overflow (),
        .underflow (),
        .mem_waddr (aw),
        .mem_wdata (dw),
        .mem_cew (cew),
        .mem_cer (cer),
        .mem_raddr (ar),
        .mem_rdata (qr)
);

endmodule

// ============================================================
//                  fifo Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : P1P060N0V324C7
// Module          : fifo2ddr
// IP core         : fifo
// IP Version      : 2

// AlmostEmpty     : false
// AlmostFull      : false
// EmptyAssert     : 30
// EmptyNegate     : 29
// EmptySingle     : 30
// EmptyType       : 0
// FifoType        : software
// FullAssert      : 60
// FullNegate      : 58
// FullSingle      : 60
// FullType        : 0
// Fwft            : true
// OverFlow        : false
// PeekMode        : false
// ReadAck         : false
// ReadAddrWidth   : 6
// ReadClr         : false
// ReadCnt         : true
// ReadDataWidth   : 128
// Regout          : false
// RegoutEn        : false
// Simulation Files: ../ip_core/fifo_v2/src/syn_fifo.v ../ip_core/fifo_v2/src/asyn_fifo.v
// Synthesis Files : src/syn_fifo.v src/asyn_fifo.v
// UnderFlow       : false
// UseHardWare     : false
// WorkMode        : false
// WriteAck        : false
// WriteAddrWidth  : 7
// WriteClr        : false
// WriteCnt        : true
// WriteDataWidth  : 64
// WriteDrop       : false
