//
// This is a file generated by DSP wizard.
// Please do not edit this file!
// Generated time: 06/17/2022 16:48:01
// Version: Fuxi fx2020a win64
// Wizard name: DSP 1.0a
//
// ============================================================
// File Name: mul_new2.v
// IP core : dsp
// Device name: P1P060N0V324I7
// ============================================================

module mul_new2(
    clk,
    rstn,
    al,
    cl,
    au,
    cu,
    r
);

input clk;
input rstn;
input [17:0] al;
input [17:0] cl;
input [17:0] au;
input [17:0] cu;
output [71:0] r;

DSP56V1 #(
        .cfg_pra_au (3'b011),
        .cfg_pra_cu (3'b011),
        .cfg_pra_du (1'b0),
        .cfg_pra_dl (1'b0),
        .cfg_pra_al (3'b010),
        .cfg_pra_cl (3'b010),
        .cfg_pra_ou (1'b0),
        .cfg_pra_ol (1'b0),
        .cfg_mult_u (2'b10),
        .cfg_mult_l (2'b10),
        .cfg_ufcmux (1'b0),
        .cfg_vldbit (56'b00000000000000000000000000000000000000000000000000000000),
        .cfg_match (1'b1),
        .cfg_imatch (1'b1),
        .cfg_poa_cyout (1'b0),
        .cfg_poa_rout (2'b00),
        .cfg_poa_ceyout (1'b0),
        .cfg_poa_ceyin (1'b0),
        .cfg_mat_clr (1'b0),
        .cfg_pazctrl (1'b0),
        .cfg_parctrl (1'b0),
        .cfg_pasubctrl (1'b0),
        .cfg_blctrl (1'b0),
        .cfg_buctrl (1'b0),
        .cfg_pasctrl (1'b0),
        .cfg_aluctrl (1'b0),
        .cfg_fcctrl (1'b0),
        .cfg_ufcctrl (1'b0),
        .cfg_subctrl (1'b0),
        .cfg_mctrl (1'b0),
        .cfg_cctrl (1'b0),
        .cfg_frctrl (1'b0),
        .cfg_rndm (1'b0)
)
u_inst1 (
        .clk (clk),
        .rstn (rstn),
        .r (r),
        .al (al),
        .cl (cl),
        .au (au),
        .cu (cu),
        .ipazctrl (6'b110011),
        .iparctrl (6'b111111),
        .ipasubctrl (2'b00),
        .iblctrl (1'b0),
        .ibuctrl (1'b0),
        .ipasctrl (8'b11100001),
        .ialuctrl (3'b000),
        .ifcctrl (3'b000),
        .iufcctrl (1'b0),
        .isubctrl (3'b000),
        .imctrl (6'b000111),
        .icctrl (3'b000),
        .ifrctrl (2'b00),
        .irndm (1'b0)
);

endmodule

// ============================================================
//                  dsp Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : P1P060N0V324I7
// Module          : mul_new2
// IP core         : dsp
// IP Version      : 1

// CompareClkEn    : false
// InputBufferClkEn: false
// LowMltClkEn     : false
// PipelineOpt     : Automatic
// PostAdderClkEn  : false
// PreAdderClkEn   : false
// Simulation Files: 
// Synthesis Files : 
// UFCClkEn        : false
// UpperMultClkEn  : false
// al              : 18
// alcasout        : false
// au              : 18
// aucasout        : false
// cl              : 18
// clcasout        : false
// cu              : 18
// cucasout        : false
// dl              : 18
// du              : 18
// function name   : cl*al+cu*au
// rcasout         : false
// u               : 56
