//
// This is a file generated by Phase-Locked Loop wizard.
// Please do not edit this file!
// Generated time: 04/13/2022 14:22:23
// Version: Fuxi fx2020a win64
// Wizard name: Phase-Locked Loop 1.0b
//
// ============================================================
// File Name: pll_main.v
// IP core : pll
// Device name: P1P060N0V324I7
// ============================================================

module pll_main(
    clkin0,
    clkout0,
    clkout1,
    clkout2,
    clkout3,
    clkout4,
    locked
);

input clkin0;
output clkout0;
output clkout1;
output clkout2;
output clkout3;
output clkout4;
output locked;

PLLV1 #(
        .CFG_SEL_FBPATH (1'b0),
        .pll_sel ("auto"),
        .input_freq ("25.00"),
        .CFG_CKSEL (1'b0),
        .CFG_CK_SWITCH_EN (1'b0),
        .CFG_DIVN (8'b00000000),
        .CFG_DIVM (8'b00101111),
        .CFG_DIVFB (1'b0),
        .CFG_LPF (3'b011),
        .CFG_CPSEL_CR (3'b011),
        .CFG_CPSEL_FN (7'b0101111),
        .CFG_CP_AUTO_ENB (1'b0),
        .CFG_RST_REG_ENB (1'b0),
        .CFG_CALIB_EN (1'b1),
        .CFG_CALIB_RSTN (1'b1),
        .CFG_CALIB_MANUAL (4'b1000),
        .CFG_CALIB_WIN (2'b00),
        .CFG_CALIB_DIV (8'b00011001),
        .CFG_CALIB_16_32U (1'b0),
        .CFG_BP_VDOUT (1'b0),
        .CFG_LKD_MUX (1'b0),
        .CFG_FORCE_LOCK (1'b0),
        .CFG_FLDD (2'b11),
        .CFG_ATEST_EN (1'b0),
        .CFG_DTEST_EN (1'b0),
        .CFG_ATEST_SEL (1'b0),
        .CFG_DTEST_SEL (1'b0),
        .CFG_VCO_INI_SEL (1'b0),
        .CFG_LKD_TOL (1'b0),
        .CFG_LKD_HOLD (1'b0),
        .CFG_VRSEL (2'b01),
        .CFG_BK (4'b0000),
        .CFG_SSEN (1'b0),
        .CFG_SSDIVH (2'b00),
        .CFG_SSDIVL (8'b11111001),
        .CFG_SSRG (2'b01),
        .CFG_PSSEL (6'b000000),
        .CFG_MKEN0 (1'b1),
        .CFG_MKEN1 (1'b1),
        .CFG_MKEN2 (1'b1),
        .CFG_MKEN3 (1'b1),
        .CFG_MKEN4 (1'b1),
        .CFG_MKEN5 (1'b0),
        .CFG_BPS0 (1'b0),
        .CFG_BPS1 (1'b0),
        .CFG_BPS2 (1'b0),
        .CFG_BPS3 (1'b0),
        .CFG_BPS4 (1'b0),
        .CFG_BPS5 (1'b0),
        .CFG_DIVC0 (8'b00001110),
        .CFG_DIVC1 (8'b00001011),
        .CFG_DIVC2 (8'b00001110),
        .CFG_DIVC3 (8'b00000101),
        .CFG_DIVC4 (8'b00101111),
        .CFG_DIVC5 (8'b00100000),
        .CFG_CO0DLY (8'b00000000),
        .CFG_CO1DLY (8'b00000000),
        .CFG_CO2DLY (8'b00000000),
        .CFG_CO3DLY (8'b00000000),
        .CFG_CO4DLY (8'b00000000),
        .CFG_CO5DLY (8'b00000000),
        .CFG_P0SEL (3'b000),
        .CFG_P1SEL (3'b000),
        .CFG_P2SEL (3'b000),
        .CFG_P3SEL (3'b000),
        .CFG_P4SEL (3'b000),
        .CFG_P5SEL (3'b000),
        .CFG_PFBSEL (3'b000),
        .CFG_RSTPLL_SEL (2'b01),
        .CFG_PPDB_SEL (2'b01),
        .CFG_LOCK_GATE (1'b1),
        .CFG_FRAC (3'b000),
        .CFG_FP_EN (1'b0)
)
pll_u0 (
        .PLLCK0 (clkin0),
        .PLLCK1 (),
        .FBIN (),
        .FP_PLL_PDB (),
        .FP_PLL_RST (),
        .ACTIVECK (),
        .CKBAD0 (),
        .CKBAD1 (),
        .CO0 (clkout0),
        .CO1 (clkout1),
        .CO2 (clkout2),
        .CO3 (clkout3),
        .CO4 (clkout4),
        .CO5 (),
        .PLOCK (locked)
);

endmodule

// ============================================================
//                  pll Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : P1P060N0V324I7
// Module          : pll_main
// IP core         : pll
// IP Version      : 1

// AutoSwitch      : false
// BandWidth       : Medium
// Bypass0         : false
// Bypass1         : false
// Bypass2         : false
// Bypass3         : false
// Bypass4         : false
// Bypass5         : false
// C0              : 14
// C1              : 11
// C2              : 14
// C3              : 5
// C4              : 47
// C5              : 32
// Clkin0Enable    : true
// Clkin1Enable    : false
// ClkinDefault    : 0
// Clkout0UseFrac  : false
// ClkoutNum       : 5
// Delay0          : 0
// Delay1          : 0
// Delay2          : 0
// Delay3          : 0
// Delay4          : 0
// Delay5          : 0
// DelayUnit       : degree
// DeskewMode      : None
// DynPhaseShift0  : false
// DynPhaseShift1  : false
// DynPhaseShift2  : false
// DynPhaseShift3  : false
// DynPhaseShift4  : false
// DynPhaseShift5  : false
// Enable0         : true
// Enable1         : true
// Enable2         : true
// Enable3         : true
// Enable4         : true
// Enable5         : false
// ForceLocked     : false
// GclkCcbEnable   : false
// InputFreq       : 25
// M               : 47
// N               : 0
// Phase0          : 0
// Phase1          : 0
// Phase2          : 0
// Phase3          : 0
// Phase4          : 0
// Phase5          : 0
// PllLocation     : auto
// PortActiveck    : false
// PortCkbad0      : false
// PortCkbad1      : false
// PortLocked      : true
// PowerMode       : always_on
// ResetMode       : ccb
// Simulation Files: 
// SpreadDivH      : 0
// SpreadDivL      : 249
// SpreadEnable    : false
// SpreadRatio     : 1
// Synthesis Files : 
// UseLockGate     : false
// VcoCalibration  : true
// VcoDivide       : 0
