//
// This is a file generated by EMB wizard.
// Please do not edit this file!
// Generated time: 06/13/2022 18:04:25
// Version: Fuxi fx2020a win64
// Wizard name: EMB 1.0b
//
// ============================================================
// File Name: KP2_RAM.v
// IP core : emb
// Device name: P1P060N0V324C7
// ============================================================

module KP2_RAM (clk, ce, we, rstn, a, d, q);
input clk;
input ce;
input we;
input rstn;
input [7:0]a;
input [17:0]d;
output [17:0]q;

wire vcc_net;
wire gnd_net;

assign vcc_net = 1;
assign gnd_net = 0;
EMB5K #(
		.clka_inv (1'b0),
		.clkb_inv (1'b0),
		.init_file (""),
		.outreg_a (1'b0),
		.outreg_b (1'b0),
		.rammode ("sp"),
		.width_a (18),
		.width_b (18),
		.writemode_a ("no_change"),
		.writemode_b ("write_first")
	)
	emb_0(
		.doa({q[16], q[15], q[14], q[13], q[12], q[11], q[10], q[9], q[7], q[6], q[5], q[4], q[3], q[2], q[1], q[0]}),
		.dob(),
		.dopa({q[17], q[8]}),
		.dopb(),
		.addra({gnd_net, gnd_net, gnd_net, gnd_net, a[7], a[6], a[5], a[4], a[3], a[2], a[1], a[0]}),
		.addrb(),
		.clka(clk),
		.clkb(),
		.dia({d[16], d[15], d[14], d[13], d[12], d[11], d[10], d[9], d[7], d[6], d[5], d[4], d[3], d[2], d[1], d[0]}),
		.dib(),
		.dipa({d[17], d[8]}),
		.dipb(),
		.cea(ce),
		.ceb(gnd_net),
		.regcea(vcc_net),
		.regceb(),
		.regsra(rstn),
		.regsrb(),
		.wea(we),
		.web()
	);
endmodule


// ============================================================
//                  emb Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : P1P060N0V324C7
// Module          : KP2_RAM
// IP core         : emb
// IP Version      : 1

// AddrUsedA       : 8
// ByteWriteEn     : false
// DataUsedA       : 18
// DataUsedB       : 18
// EmbResource     : AUTO
// EmbType         : sp
// ErrorInjectMode : None
// InitFile        : 
// RegoutA         : false
// RegoutB         : false
// RegoutEnA       : false
// RegoutEnB       : false
// Simulation Files: 
// SplitEmb        : false
// SplitInfo       : 18,256;block_0:18,256,0,0,0 1 2 3 4 5 6 7 9 10 11 12 13 14 15 16 8 17
// Synthesis Files : 
// UseEccEn        : false
// WriteModeA      : No Change
// WriteModeB      : Write First
