//
// This is a file generated by EMB wizard.
// Please do not edit this file!
// Generated time: 06/21/2022 20:13:57
// Version: Fuxi fx2020a win64
// Wizard name: EMB 1.0b
//
// ============================================================
// File Name: NMS.v
// IP core : emb
// Device name: P1P060N0V324C7
// ============================================================

module NMS (clk, ce, we, rstn, a, d, q);
input clk;
input ce;
input we;
input rstn;
input [17:0]a;
input [0:0]d;
output [0:0]q;

wire vcc_net;
wire gnd_net;
wire net_2;
wire net_18;
wire net_20;
wire net_21;
wire addra_pipe_14_net;
wire net_23;
wire net_24;
wire net_26;
wire net_27;
wire net_28;
wire net_29;
wire net_30;
wire net_31;
wire net_32;
wire net_33;
wire net_34;
wire net_35;
wire addra_pipe_15_net;
wire net_36;
wire net_37;
wire net_39;
wire net_40;
wire net_41;
wire net_42;
wire net_43;
wire net_44;
wire net_45;
wire net_46;
wire net_47;
wire net_48;
wire net_49;
wire net_50;
wire net_51;
wire net_52;
wire net_53;
wire net_54;
wire net_55;
wire net_56;
wire net_57;
wire net_58;
wire addra_pipe_16_net;
wire net_59;
wire net_60;
wire net_62;
wire net_63;
wire net_64;
wire net_65;
wire net_66;
wire net_67;
wire net_68;
wire net_69;
wire net_70;
wire net_71;
wire net_72;
wire net_73;
wire net_74;
wire net_75;
wire net_76;
wire net_77;
wire net_78;
wire net_79;
wire net_80;
wire net_81;
wire net_82;
wire net_83;
wire net_84;
wire net_85;
wire net_86;
wire net_87;
wire net_88;
wire net_89;
wire net_90;
wire net_91;
wire net_92;
wire net_93;
wire net_94;
wire net_95;
wire net_96;
wire net_97;
wire net_98;
wire net_99;
wire net_100;
wire net_101;
wire addra_pipe_17_net;
wire net_102;
wire net_103;
wire net_106;
wire nc1;
wire nc2;
wire nc3;
wire nc4;
wire nc5;
wire nc6;
wire nc7;
wire nc8;
wire nc9;
wire nc10;
wire nc11;
wire nc12;
wire nc13;
wire nc14;
wire nc15;
wire nc16;
wire nc17;
wire nc18;
wire nc19;
wire nc20;
wire nc21;
wire nc22;
wire nc23;
wire nc24;
wire nc25;
wire nc26;
wire nc27;
wire nc28;
wire nc29;
wire nc30;
wire nc31;
wire nc32;
wire nc33;
wire nc34;
wire nc35;
wire nc36;
wire nc37;
wire nc38;
wire nc39;
wire nc40;
wire nc41;
wire nc42;
wire nc43;
wire nc44;
wire nc45;
wire nc46;
wire nc47;
wire nc48;
wire nc49;
wire nc50;
wire nc51;
wire nc52;
wire nc53;
wire nc54;
wire nc55;
wire nc56;
wire nc57;
wire nc58;
wire nc59;
wire nc60;
wire nc61;
wire nc62;
wire nc63;
wire nc64;
wire nc65;
wire nc66;
wire nc67;
wire nc68;
wire nc69;
wire nc70;
wire nc71;
wire nc72;
wire nc73;
wire nc74;
wire nc75;
wire nc76;
wire nc77;
wire nc78;
wire nc79;
wire nc80;
wire nc81;
wire nc82;
wire nc83;
wire nc84;
wire nc85;
wire nc86;
wire nc87;
wire nc88;
wire nc89;
wire nc90;
wire nc91;
wire nc92;
wire nc93;
wire nc94;
wire nc95;
wire nc96;
wire nc97;
wire nc98;
wire nc99;
wire nc100;
wire nc101;
wire nc102;
wire nc103;
wire nc104;
wire nc105;
wire nc106;
wire nc107;
wire nc108;
wire nc109;
wire nc110;
wire nc111;
wire nc112;
wire nc113;
wire nc114;
wire nc115;
wire nc116;
wire nc117;
wire nc118;
wire nc119;
wire nc120;
wire nc121;
wire nc122;
wire nc123;
wire nc124;
wire nc125;
wire nc126;
wire nc127;
wire nc128;
wire nc129;
wire nc130;
wire nc131;
wire nc132;
wire nc133;
wire nc134;
wire nc135;
wire nc136;
wire nc137;
wire nc138;
wire nc139;
wire nc140;
wire nc141;
wire nc142;
wire nc143;
wire nc144;
wire nc145;
wire nc146;
wire nc147;
wire nc148;
wire nc149;
wire nc150;
wire nc151;
wire nc152;
wire nc153;
wire nc154;
wire nc155;
wire nc156;
wire nc157;
wire nc158;
wire nc159;
wire nc160;
wire nc161;
wire nc162;
wire nc163;
wire nc164;
wire nc165;
wire nc166;
wire nc167;
wire nc168;
wire nc169;
wire nc170;
wire nc171;
wire nc172;
wire nc173;
wire nc174;
wire nc175;
wire nc176;
wire nc177;
wire nc178;
wire nc179;
wire nc180;
wire nc181;
wire nc182;
wire nc183;
wire nc184;
wire nc185;
wire nc186;
wire nc187;
wire nc188;
wire nc189;
wire nc190;
wire nc191;
wire nc192;
wire nc193;
wire nc194;
wire nc195;
wire nc196;
wire nc197;
wire nc198;
wire nc199;
wire nc200;
wire nc201;
wire nc202;
wire nc203;
wire nc204;
wire nc205;
wire nc206;
wire nc207;
wire nc208;
wire nc209;
wire nc210;
wire nc211;
wire nc212;
wire nc213;
wire nc214;
wire nc215;
wire nc216;
wire nc217;
wire nc218;
wire nc219;
wire nc220;
wire nc221;
wire nc222;
wire nc223;
wire nc224;
wire nc225;
wire nc226;
wire nc227;
wire nc228;
wire nc229;
wire nc230;
wire nc231;
wire nc232;
wire nc233;
wire nc234;
wire nc235;
wire nc236;
wire nc237;
wire nc238;
wire nc239;
wire nc240;
wire nc241;
wire nc242;
wire nc243;
wire nc244;
wire nc245;
wire nc246;
wire nc247;
wire nc248;
wire nc249;
wire nc250;
wire nc251;
wire nc252;
wire nc253;
wire nc254;
wire nc255;
wire nc256;
wire nc257;
wire nc258;
wire nc259;
wire nc260;
wire nc261;
wire nc262;
wire nc263;
wire nc264;
wire nc265;
wire nc266;
wire nc267;
wire nc268;
wire nc269;
wire nc270;
wire nc271;
wire nc272;
wire nc273;
wire nc274;
wire nc275;
wire nc276;
wire nc277;
wire nc278;
wire nc279;
wire nc280;
wire nc281;
wire nc282;
wire nc283;
wire nc284;
wire nc285;
wire nc286;
wire nc287;
wire nc288;
wire nc289;
wire nc290;
wire nc291;
wire nc292;
wire nc293;
wire nc294;
wire nc295;
wire nc296;
wire nc297;
wire nc298;
wire nc299;
wire nc300;
wire nc301;
wire nc302;
wire nc303;
wire nc304;
wire nc305;
wire nc306;
wire nc307;
wire nc308;
wire nc309;
wire nc310;
wire nc311;
wire nc312;
wire nc313;
wire nc314;
wire nc315;
wire nc316;
wire nc317;
wire nc318;
wire nc319;
wire nc320;
wire nc321;
wire nc322;
wire nc323;
wire nc324;
wire nc325;
wire nc326;
wire nc327;
wire nc328;
wire nc329;
wire nc330;
wire nc331;
wire nc332;
wire nc333;
wire nc334;
wire nc335;
wire nc336;
wire nc337;
wire nc338;
wire nc339;
wire nc340;
wire nc341;
wire nc342;
wire nc343;
wire nc344;
wire nc345;
wire nc346;
wire nc347;
wire nc348;
wire nc349;
wire nc350;
wire nc351;
wire nc352;
wire nc353;
wire nc354;
wire nc355;
wire nc356;
wire nc357;
wire nc358;
wire nc359;
wire nc360;
wire nc361;
wire nc362;
wire nc363;
wire nc364;
wire nc365;
wire nc366;
wire nc367;
wire nc368;
wire nc369;
wire nc370;
wire nc371;
wire nc372;
wire nc373;
wire nc374;
wire nc375;
wire nc376;
wire nc377;
wire nc378;
wire nc379;
wire nc380;
wire nc381;
wire nc382;
wire nc383;
wire nc384;
wire nc385;
wire nc386;
wire nc387;
wire nc388;
wire nc389;
wire nc390;
wire nc391;
wire nc392;
wire nc393;
wire nc394;
wire nc395;
wire nc396;
wire nc397;
wire nc398;
wire nc399;
wire nc400;
wire nc401;
wire nc402;
wire nc403;
wire nc404;
wire nc405;
wire nc406;
wire nc407;
wire nc408;
wire nc409;
wire nc410;
wire nc411;
wire nc412;
wire nc413;
wire nc414;
wire nc415;
wire nc416;
wire nc417;
wire nc418;
wire nc419;
wire nc420;
wire nc421;
wire nc422;
wire nc423;
wire nc424;
wire nc425;
wire nc426;
wire nc427;
wire nc428;
wire nc429;
wire nc430;
wire nc431;
wire nc432;
wire nc433;
wire nc434;
wire nc435;
wire nc436;
wire nc437;
wire nc438;
wire nc439;
wire nc440;
wire nc441;
wire nc442;
wire nc443;
wire nc444;
wire nc445;
wire nc446;
wire nc447;
wire nc448;
wire nc449;
wire nc450;
wire nc451;
wire nc452;
wire nc453;
wire nc454;
wire nc455;
wire nc456;
wire nc457;
wire nc458;
wire nc459;
wire nc460;
wire nc461;
wire nc462;
wire nc463;
wire nc464;
wire nc465;
wire nc466;
wire nc467;
wire nc468;
wire nc469;
wire nc470;
wire nc471;
wire nc472;
wire nc473;
wire nc474;
wire nc475;
wire nc476;
wire nc477;
wire nc478;
wire nc479;
wire nc480;
wire nc481;
wire nc482;
wire nc483;
wire nc484;
wire nc485;
wire nc486;
wire nc487;
wire nc488;
wire nc489;
wire nc490;
wire nc491;
wire nc492;
wire nc493;
wire nc494;
wire nc495;
wire nc496;
wire nc497;
wire nc498;
wire nc499;
wire nc500;
wire nc501;
wire nc502;
wire nc503;
wire nc504;
wire nc505;
wire nc506;
wire nc507;
wire nc508;
wire nc509;
wire nc510;
wire nc511;
wire nc512;
wire nc513;
wire nc514;
wire nc515;
wire nc516;
wire nc517;
wire nc518;
wire nc519;
wire nc520;
wire nc521;
wire nc522;
wire nc523;
wire nc524;
wire nc525;
wire nc526;
wire nc527;
wire nc528;
wire nc529;
wire nc530;
wire nc531;
wire nc532;
wire nc533;
wire nc534;
wire nc535;
wire nc536;
wire nc537;
wire nc538;
wire nc539;
wire nc540;
wire nc541;
wire nc542;
wire nc543;
wire nc544;
wire nc545;
wire nc546;
wire nc547;
wire nc548;
wire nc549;
wire nc550;
wire nc551;
wire nc552;
wire nc553;
wire nc554;
wire nc555;
wire nc556;
wire nc557;
wire nc558;
wire nc559;
wire nc560;
wire nc561;
wire nc562;
wire nc563;
wire nc564;
wire nc565;
wire nc566;
wire nc567;
wire nc568;
wire nc569;
wire nc570;
wire nc571;
wire nc572;
wire nc573;
wire nc574;
wire nc575;
wire nc576;
wire nc577;
wire nc578;
wire nc579;
wire nc580;
wire nc581;
wire nc582;
wire nc583;
wire nc584;
wire nc585;
wire nc586;
wire nc587;
wire nc588;
wire nc589;
wire nc590;
wire nc591;
wire nc592;
wire nc593;
wire nc594;
wire nc595;
wire nc596;
wire nc597;
wire nc598;
wire nc599;
wire nc600;
wire nc601;
wire nc602;
wire nc603;
wire nc604;
wire nc605;
wire nc606;
wire nc607;
wire nc608;
wire nc609;
wire nc610;
wire nc611;
wire nc612;
wire nc613;
wire nc614;
wire nc615;
wire nc616;
wire nc617;
wire nc618;
wire nc619;
wire nc620;
wire nc621;
wire nc622;
wire nc623;
wire nc624;
wire nc625;
wire nc626;
wire nc627;
wire nc628;
wire nc629;
wire nc630;
wire nc631;
wire nc632;
wire nc633;
wire nc634;
wire nc635;
wire nc636;
wire nc637;
wire nc638;
wire nc639;
wire nc640;
wire nc641;
wire nc642;
wire nc643;
wire nc644;
wire nc645;
wire nc646;
wire nc647;
wire nc648;
wire nc649;
wire nc650;
wire nc651;
wire nc652;
wire nc653;
wire nc654;
wire nc655;
wire nc656;
wire nc657;
wire nc658;
wire nc659;
wire nc660;
wire nc661;
wire nc662;
wire nc663;
wire nc664;
wire nc665;
wire nc666;
wire nc667;
wire nc668;
wire nc669;
wire nc670;
wire nc671;
wire nc672;
wire nc673;
wire nc674;
wire nc675;
wire nc676;
wire nc677;
wire nc678;
wire nc679;
wire nc680;
wire nc681;
wire nc682;
wire nc683;
wire nc684;
wire nc685;
wire nc686;
wire nc687;
wire nc688;
wire nc689;
wire nc690;
wire nc691;
wire nc692;
wire nc693;
wire nc694;
wire nc695;
wire nc696;
wire nc697;
wire nc698;
wire nc699;
wire nc700;
wire nc701;
wire nc702;
wire nc703;
wire nc704;
wire nc705;
wire nc706;
wire nc707;
wire nc708;
wire nc709;
wire nc710;
wire nc711;
wire nc712;
wire nc713;
wire nc714;
wire nc715;
wire nc716;
wire nc717;
wire nc718;
wire nc719;
wire nc720;
wire nc721;
wire nc722;
wire nc723;
wire nc724;
wire nc725;
wire nc726;
wire nc727;
wire nc728;
wire nc729;
wire nc730;
wire nc731;
wire nc732;
wire nc733;
wire nc734;
wire nc735;
wire nc736;
wire nc737;
wire nc738;
wire nc739;
wire nc740;
wire nc741;
wire nc742;
wire nc743;
wire nc744;
wire nc745;
wire nc746;
wire nc747;
wire nc748;
wire nc749;
wire nc750;
wire nc751;
wire nc752;
wire nc753;
wire nc754;
wire nc755;
wire nc756;
wire nc757;
wire nc758;
wire nc759;
wire nc760;
wire nc761;
wire nc762;
wire nc763;
wire nc764;
wire nc765;
wire nc766;
wire nc767;
wire nc768;
wire nc769;
wire nc770;
wire nc771;
wire nc772;
wire nc773;
wire nc774;
wire nc775;
wire nc776;
wire nc777;
wire nc778;
wire nc779;
wire nc780;
wire nc781;
wire nc782;
wire nc783;
wire nc784;
wire nc785;
wire nc786;
wire nc787;
wire nc788;
wire nc789;
wire nc790;
wire nc791;
wire nc792;
wire nc793;
wire nc794;
wire nc795;
wire nc796;
wire nc797;
wire nc798;
wire nc799;
wire nc800;
wire nc801;
wire nc802;
wire nc803;
wire nc804;
wire nc805;
wire nc806;
wire nc807;
wire nc808;
wire nc809;
wire nc810;
wire nc811;
wire nc812;
wire nc813;
wire nc814;
wire nc815;
wire nc816;
wire nc817;
wire nc818;
wire nc819;
wire nc820;
wire nc821;
wire nc822;
wire nc823;
wire nc824;
wire nc825;
wire nc826;
wire nc827;
wire nc828;
wire nc829;
wire nc830;
wire nc831;
wire nc832;
wire nc833;
wire nc834;
wire nc835;
wire nc836;
wire nc837;
wire nc838;
wire nc839;
wire nc840;
wire nc841;
wire nc842;
wire nc843;
wire nc844;
wire nc845;
wire nc846;
wire nc847;
wire nc848;
wire nc849;
wire nc850;
wire nc851;
wire nc852;
wire nc853;
wire nc854;
wire nc855;
wire nc856;
wire nc857;
wire nc858;
wire nc859;
wire nc860;
wire nc861;
wire nc862;
wire nc863;
wire nc864;
wire nc865;
wire nc866;
wire nc867;
wire nc868;
wire nc869;
wire nc870;
wire nc871;
wire nc872;
wire nc873;
wire nc874;
wire nc875;
wire nc876;
wire nc877;
wire nc878;
wire nc879;
wire nc880;
wire nc881;
wire nc882;
wire nc883;
wire nc884;
wire nc885;
wire nc886;
wire nc887;
wire nc888;
wire nc889;
wire nc890;
wire nc891;
wire nc892;
wire nc893;
wire nc894;
wire nc895;
wire nc896;
wire nc897;
wire nc898;
wire nc899;
wire nc900;
wire nc901;
wire nc902;
wire nc903;
wire nc904;
wire nc905;
wire nc906;
wire nc907;
wire nc908;
wire nc909;
wire nc910;
wire nc911;
wire nc912;
wire nc913;
wire nc914;
wire nc915;
wire nc916;
wire nc917;
wire nc918;
wire nc919;
wire nc920;
wire nc921;
wire nc922;
wire nc923;
wire nc924;
wire nc925;
wire nc926;
wire nc927;
wire nc928;
wire nc929;
wire nc930;
wire nc931;
wire nc932;
wire nc933;
wire nc934;
wire nc935;
wire nc936;
wire nc937;
wire nc938;
wire nc939;
wire nc940;
wire nc941;
wire nc942;
wire nc943;
wire nc944;
wire nc945;
wire nc946;
wire nc947;
wire nc948;
wire nc949;
wire nc950;
wire nc951;
wire nc952;
wire nc953;
wire nc954;
wire nc955;
wire nc956;
wire nc957;
wire nc958;
wire nc959;
wire nc960;
wire nc961;
wire nc962;
wire nc963;
wire nc964;
wire nc965;
wire nc966;
wire nc967;
wire nc968;
wire nc969;
wire nc970;
wire nc971;
wire nc972;
wire nc973;
wire nc974;
wire nc975;
wire nc976;
wire nc977;
wire nc978;
wire nc979;
wire nc980;
wire nc981;
wire nc982;
wire nc983;
wire nc984;
wire nc985;
wire nc986;
wire nc987;
wire nc988;
wire nc989;
wire nc990;
wire nc991;
wire nc992;
wire nc993;
wire nc994;
wire nc995;
wire nc996;
wire nc997;
wire nc998;
wire nc999;
wire nc1000;
wire nc1001;
wire nc1002;
wire nc1003;
wire nc1004;
wire nc1005;
wire nc1006;
wire nc1007;
wire nc1008;
wire nc1009;
wire nc1010;
wire nc1011;
wire nc1012;
wire nc1013;
wire nc1014;
wire nc1015;
wire nc1016;
wire nc1017;
wire nc1018;
wire nc1019;
wire nc1020;
wire nc1021;
wire nc1022;
wire nc1023;
wire nc1024;
wire nc1025;
wire nc1026;
wire nc1027;
wire nc1028;
wire nc1029;
wire nc1030;
wire nc1031;
wire nc1032;
wire nc1033;
wire nc1034;
wire nc1035;
wire nc1036;
wire nc1037;
wire nc1038;
wire nc1039;
wire nc1040;
wire nc1041;
wire nc1042;
wire nc1043;
wire nc1044;
wire nc1045;
wire nc1046;
wire nc1047;
wire nc1048;
wire nc1049;
wire nc1050;
wire nc1051;
wire nc1052;
wire nc1053;
wire nc1054;
wire nc1055;
wire nc1056;
wire nc1057;
wire nc1058;
wire nc1059;
wire nc1060;
wire nc1061;
wire nc1062;
wire nc1063;
wire nc1064;
wire nc1065;
wire nc1066;
wire nc1067;
wire nc1068;
wire nc1069;
wire nc1070;
wire nc1071;
wire nc1072;
wire nc1073;
wire nc1074;
wire nc1075;
wire nc1076;
wire nc1077;
wire nc1078;
wire nc1079;
wire nc1080;
wire nc1081;
wire nc1082;
wire nc1083;
wire nc1084;
wire nc1085;
wire nc1086;
wire nc1087;
wire nc1088;
wire nc1089;
wire nc1090;
wire nc1091;
wire nc1092;
wire nc1093;
wire nc1094;
wire nc1095;
wire nc1096;
wire nc1097;
wire nc1098;
wire nc1099;
wire nc1100;
wire nc1101;
wire nc1102;
wire nc1103;
wire nc1104;
wire nc1105;
wire nc1106;
wire nc1107;
wire nc1108;
wire nc1109;
wire nc1110;
wire nc1111;
wire nc1112;
wire nc1113;
wire nc1114;
wire nc1115;
wire nc1116;
wire nc1117;
wire nc1118;
wire nc1119;
wire nc1120;
wire nc1121;
wire nc1122;
wire nc1123;
wire nc1124;
wire nc1125;
wire nc1126;
wire nc1127;
wire nc1128;
wire nc1129;
wire nc1130;
wire nc1131;
wire nc1132;
wire nc1133;
wire nc1134;
wire nc1135;
wire nc1136;
wire nc1137;
wire nc1138;
wire nc1139;
wire nc1140;
wire nc1141;
wire nc1142;
wire nc1143;
wire nc1144;
wire nc1145;
wire nc1146;
wire nc1147;
wire nc1148;
wire nc1149;
wire nc1150;
wire nc1151;
wire nc1152;
wire nc1153;
wire nc1154;
wire nc1155;
wire nc1156;
wire nc1157;
wire nc1158;
wire nc1159;
wire nc1160;
wire nc1161;
wire nc1162;
wire nc1163;
wire nc1164;
wire nc1165;
wire nc1166;
wire nc1167;
wire nc1168;
wire nc1169;
wire nc1170;
wire nc1171;
wire nc1172;
wire nc1173;
wire nc1174;
wire nc1175;
wire nc1176;
wire nc1177;
wire nc1178;
wire nc1179;
wire nc1180;
wire nc1181;
wire nc1182;
wire nc1183;
wire nc1184;
wire nc1185;
wire nc1186;
wire nc1187;
wire nc1188;
wire nc1189;
wire nc1190;
wire nc1191;
wire nc1192;
wire nc1193;
wire nc1194;
wire nc1195;
wire nc1196;
wire nc1197;
wire nc1198;
wire nc1199;
wire nc1200;
wire nc1201;
wire nc1202;
wire nc1203;
wire nc1204;
wire nc1205;
wire nc1206;
wire nc1207;
wire nc1208;
wire nc1209;
wire nc1210;
wire nc1211;
wire nc1212;
wire nc1213;
wire nc1214;
wire nc1215;
wire nc1216;
wire nc1217;
wire nc1218;
wire nc1219;
wire nc1220;
wire nc1221;
wire nc1222;
wire nc1223;
wire nc1224;
wire nc1225;
wire nc1226;
wire nc1227;
wire nc1228;
wire nc1229;
wire nc1230;
wire nc1231;
wire nc1232;
wire nc1233;
wire nc1234;
wire nc1235;
wire nc1236;
wire nc1237;
wire nc1238;
wire nc1239;
wire nc1240;
wire nc1241;
wire nc1242;
wire nc1243;
wire nc1244;
wire nc1245;
wire nc1246;
wire nc1247;
wire nc1248;
wire nc1249;
wire nc1250;
wire nc1251;
wire nc1252;
wire nc1253;
wire nc1254;
wire nc1255;
wire nc1256;
wire nc1257;
wire nc1258;
wire nc1259;
wire nc1260;
wire nc1261;
wire nc1262;
wire nc1263;
wire nc1264;
wire nc1265;
wire nc1266;
wire nc1267;
wire nc1268;
wire nc1269;
wire nc1270;
wire nc1271;
wire nc1272;
wire nc1273;
wire nc1274;
wire nc1275;
wire nc1276;
wire nc1277;
wire nc1278;
wire nc1279;
wire nc1280;
wire nc1281;
wire nc1282;
wire nc1283;
wire nc1284;
wire nc1285;
wire nc1286;
wire nc1287;
wire nc1288;
wire nc1289;
wire nc1290;
wire nc1291;
wire nc1292;
wire nc1293;
wire nc1294;
wire nc1295;
wire nc1296;
wire nc1297;
wire nc1298;
wire nc1299;
wire nc1300;
wire nc1301;
wire nc1302;
wire nc1303;
wire nc1304;
wire nc1305;
wire nc1306;
wire nc1307;
wire nc1308;
wire nc1309;
wire nc1310;
wire nc1311;
wire nc1312;
wire nc1313;
wire nc1314;
wire nc1315;
wire nc1316;
wire nc1317;
wire nc1318;
wire nc1319;
wire nc1320;
wire nc1321;
wire nc1322;
wire nc1323;
wire nc1324;
wire nc1325;
wire nc1326;
wire nc1327;
wire nc1328;
wire nc1329;
wire nc1330;
wire nc1331;
wire nc1332;
wire nc1333;
wire nc1334;
wire nc1335;
wire nc1336;
wire nc1337;
wire nc1338;
wire nc1339;
wire nc1340;
wire nc1341;
wire nc1342;
wire nc1343;
wire nc1344;
wire nc1345;
wire nc1346;
wire nc1347;
wire nc1348;
wire nc1349;
wire nc1350;
wire nc1351;
wire nc1352;
wire nc1353;
wire nc1354;
wire nc1355;
wire nc1356;
wire nc1357;
wire nc1358;
wire nc1359;
wire nc1360;
wire nc1361;
wire nc1362;
wire nc1363;
wire nc1364;
wire nc1365;
wire nc1366;
wire nc1367;
wire nc1368;
wire nc1369;
wire nc1370;
wire nc1371;
wire nc1372;
wire nc1373;
wire nc1374;
wire nc1375;
wire nc1376;
wire nc1377;
wire nc1378;
wire nc1379;
wire nc1380;
wire nc1381;
wire nc1382;
wire nc1383;
wire nc1384;
wire nc1385;
wire nc1386;
wire nc1387;
wire nc1388;
wire nc1389;
wire nc1390;
wire nc1391;
wire nc1392;
wire nc1393;
wire nc1394;
wire nc1395;
wire nc1396;
wire nc1397;
wire nc1398;
wire nc1399;
wire nc1400;
wire nc1401;
wire nc1402;
wire nc1403;
wire nc1404;
wire nc1405;
wire nc1406;
wire nc1407;
wire nc1408;
wire nc1409;
wire nc1410;
wire nc1411;
wire nc1412;
wire nc1413;
wire nc1414;
wire nc1415;
wire nc1416;
wire nc1417;
wire nc1418;
wire nc1419;
wire nc1420;
wire nc1421;
wire nc1422;
wire nc1423;
wire nc1424;
wire nc1425;
wire nc1426;
wire nc1427;
wire nc1428;
wire nc1429;
wire nc1430;
wire nc1431;
wire nc1432;
wire nc1433;
wire nc1434;
wire nc1435;
wire nc1436;
wire nc1437;
wire nc1438;
wire nc1439;
wire nc1440;
wire nc1441;
wire nc1442;
wire nc1443;
wire nc1444;
wire nc1445;
wire nc1446;
wire nc1447;
wire nc1448;
wire nc1449;
wire nc1450;
wire nc1451;
wire nc1452;
wire nc1453;
wire nc1454;
wire nc1455;
wire nc1456;
wire nc1457;
wire nc1458;
wire nc1459;
wire nc1460;
wire nc1461;
wire nc1462;
wire nc1463;
wire nc1464;
wire nc1465;
wire nc1466;
wire nc1467;
wire nc1468;
wire nc1469;
wire nc1470;
wire nc1471;
wire nc1472;
wire nc1473;
wire nc1474;
wire nc1475;
wire nc1476;
wire nc1477;
wire nc1478;
wire nc1479;
wire nc1480;
wire nc1481;
wire nc1482;
wire nc1483;
wire nc1484;
wire nc1485;
wire nc1486;
wire nc1487;
wire nc1488;
wire nc1489;
wire nc1490;
wire nc1491;
wire nc1492;
wire nc1493;
wire nc1494;
wire nc1495;
wire nc1496;
wire nc1497;
wire nc1498;
wire nc1499;
wire nc1500;
wire nc1501;
wire nc1502;
wire nc1503;
wire nc1504;
wire nc1505;
wire nc1506;
wire nc1507;
wire nc1508;
wire nc1509;
wire nc1510;
wire nc1511;
wire nc1512;
wire nc1513;
wire nc1514;
wire nc1515;
wire nc1516;
wire nc1517;
wire nc1518;
wire nc1519;
wire nc1520;
wire nc1521;
wire nc1522;
wire nc1523;
wire nc1524;
wire nc1525;
wire nc1526;
wire nc1527;
wire nc1528;
wire nc1529;
wire nc1530;
wire nc1531;
wire nc1532;
wire nc1533;
wire nc1534;
wire nc1535;
wire nc1536;
wire nc1537;
wire nc1538;
wire nc1539;
wire nc1540;
wire nc1541;
wire nc1542;
wire nc1543;
wire nc1544;
wire nc1545;
wire nc1546;
wire nc1547;
wire nc1548;
wire nc1549;
wire nc1550;
wire nc1551;
wire nc1552;
wire nc1553;
wire nc1554;
wire nc1555;
wire nc1556;
wire nc1557;
wire nc1558;
wire nc1559;
wire nc1560;
wire nc1561;
wire nc1562;
wire nc1563;
wire nc1564;
wire nc1565;
wire nc1566;
wire nc1567;
wire nc1568;
wire nc1569;
wire nc1570;
wire nc1571;
wire nc1572;
wire nc1573;
wire nc1574;
wire nc1575;
wire nc1576;
wire nc1577;
wire nc1578;
wire nc1579;
wire nc1580;
wire nc1581;
wire nc1582;
wire nc1583;
wire nc1584;
wire nc1585;
wire nc1586;
wire nc1587;
wire nc1588;
wire nc1589;
wire nc1590;
wire nc1591;
wire nc1592;
wire nc1593;
wire nc1594;
wire nc1595;
wire nc1596;
wire nc1597;
wire nc1598;
wire nc1599;
wire nc1600;
wire nc1601;
wire nc1602;
wire nc1603;
wire nc1604;
wire nc1605;
wire nc1606;
wire nc1607;
wire nc1608;
wire nc1609;
wire nc1610;
wire nc1611;
wire nc1612;
wire nc1613;
wire nc1614;
wire nc1615;
wire nc1616;
wire nc1617;
wire nc1618;
wire nc1619;
wire nc1620;
wire nc1621;
wire nc1622;
wire nc1623;
wire nc1624;
wire nc1625;
wire nc1626;
wire nc1627;
wire nc1628;
wire nc1629;
wire nc1630;
wire nc1631;
wire nc1632;
wire nc1633;
wire nc1634;
wire nc1635;
wire nc1636;
wire nc1637;
wire nc1638;
wire nc1639;
wire nc1640;
wire nc1641;
wire nc1642;
wire nc1643;
wire nc1644;
wire nc1645;
wire nc1646;
wire nc1647;
wire nc1648;
wire nc1649;
wire nc1650;
wire nc1651;
wire nc1652;
wire nc1653;
wire nc1654;
wire nc1655;
wire nc1656;
wire nc1657;
wire nc1658;
wire nc1659;
wire nc1660;
wire nc1661;
wire nc1662;
wire nc1663;
wire nc1664;
wire nc1665;
wire nc1666;
wire nc1667;
wire nc1668;
wire nc1669;
wire nc1670;
wire nc1671;
wire nc1672;
wire nc1673;
wire nc1674;
wire nc1675;
wire nc1676;
wire nc1677;
wire nc1678;
wire nc1679;
wire nc1680;
wire nc1681;
wire nc1682;
wire nc1683;
wire nc1684;
wire nc1685;
wire nc1686;
wire nc1687;
wire nc1688;
wire nc1689;
wire nc1690;
wire nc1691;
wire nc1692;
wire nc1693;
wire nc1694;
wire nc1695;
wire nc1696;
wire nc1697;
wire nc1698;
wire nc1699;
wire nc1700;
wire nc1701;
wire nc1702;
wire nc1703;
wire nc1704;
wire nc1705;
wire nc1706;
wire nc1707;
wire nc1708;
wire nc1709;
wire nc1710;
wire nc1711;
wire nc1712;
wire nc1713;
wire nc1714;
wire nc1715;
wire nc1716;
wire nc1717;
wire nc1718;
wire nc1719;
wire nc1720;
wire nc1721;
wire nc1722;
wire nc1723;
wire nc1724;
wire nc1725;
wire nc1726;
wire nc1727;
wire nc1728;
wire nc1729;
wire nc1730;
wire nc1731;
wire nc1732;
wire nc1733;
wire nc1734;
wire nc1735;
wire nc1736;
wire nc1737;
wire nc1738;
wire nc1739;
wire nc1740;
wire nc1741;
wire nc1742;
wire nc1743;
wire nc1744;
wire nc1745;
wire nc1746;
wire nc1747;
wire nc1748;
wire nc1749;
wire nc1750;
wire nc1751;
wire nc1752;
wire nc1753;
wire nc1754;
wire nc1755;
wire nc1756;
wire nc1757;
wire nc1758;
wire nc1759;
wire nc1760;
wire nc1761;
wire nc1762;
wire nc1763;
wire nc1764;
wire nc1765;
wire nc1766;
wire nc1767;
wire nc1768;
wire nc1769;
wire nc1770;
wire nc1771;
wire nc1772;
wire nc1773;
wire nc1774;
wire nc1775;
wire nc1776;
wire nc1777;
wire nc1778;
wire nc1779;
wire nc1780;
wire nc1781;
wire nc1782;
wire nc1783;
wire nc1784;
wire nc1785;
wire nc1786;
wire nc1787;
wire nc1788;
wire nc1789;
wire nc1790;
wire nc1791;
wire nc1792;
wire nc1793;
wire nc1794;
wire nc1795;
wire nc1796;
wire nc1797;
wire nc1798;
wire nc1799;
wire nc1800;
wire nc1801;
wire nc1802;
wire nc1803;
wire nc1804;
wire nc1805;
wire nc1806;
wire nc1807;
wire nc1808;
wire nc1809;
wire nc1810;
wire nc1811;
wire nc1812;
wire nc1813;
wire nc1814;
wire nc1815;
wire nc1816;
wire nc1817;
wire nc1818;
wire nc1819;
wire nc1820;
wire nc1821;
wire nc1822;
wire nc1823;
wire nc1824;
wire nc1825;
wire nc1826;
wire nc1827;
wire nc1828;
wire nc1829;
wire nc1830;
wire nc1831;
wire nc1832;
wire nc1833;
wire nc1834;
wire nc1835;
wire nc1836;
wire nc1837;
wire nc1838;
wire nc1839;
wire nc1840;
wire nc1841;
wire nc1842;
wire nc1843;
wire nc1844;
wire nc1845;
wire nc1846;
wire nc1847;
wire nc1848;
wire nc1849;
wire nc1850;
wire nc1851;
wire nc1852;
wire nc1853;
wire nc1854;
wire nc1855;
wire nc1856;
wire nc1857;
wire nc1858;
wire nc1859;
wire nc1860;
wire nc1861;
wire nc1862;
wire nc1863;
wire nc1864;
wire nc1865;
wire nc1866;
wire nc1867;
wire nc1868;
wire nc1869;
wire nc1870;
wire nc1871;
wire nc1872;
wire nc1873;
wire nc1874;
wire nc1875;
wire nc1876;
wire nc1877;
wire nc1878;
wire nc1879;
wire nc1880;
wire nc1881;
wire nc1882;
wire nc1883;
wire nc1884;
wire nc1885;
wire nc1886;
wire nc1887;
wire nc1888;
wire nc1889;
wire nc1890;
wire nc1891;
wire nc1892;
wire nc1893;
wire nc1894;
wire nc1895;
wire nc1896;
wire nc1897;
wire nc1898;
wire nc1899;
wire nc1900;
wire nc1901;
wire nc1902;
wire nc1903;
wire nc1904;
wire nc1905;
wire nc1906;
wire nc1907;
wire nc1908;
wire nc1909;
wire nc1910;
wire nc1911;
wire nc1912;
wire nc1913;
wire nc1914;
wire nc1915;
wire nc1916;
wire nc1917;
wire nc1918;
wire nc1919;
wire nc1920;
wire nc1921;
wire nc1922;
wire nc1923;
wire nc1924;
wire nc1925;
wire nc1926;
wire nc1927;
wire nc1928;
wire nc1929;
wire nc1930;
wire nc1931;
wire nc1932;
wire nc1933;
wire nc1934;
wire nc1935;
wire nc1936;
wire nc1937;
wire nc1938;
wire nc1939;
wire nc1940;
wire nc1941;
wire nc1942;
wire nc1943;
wire nc1944;
wire nc1945;
wire nc1946;
wire nc1947;
wire nc1948;
wire nc1949;
wire nc1950;
wire nc1951;
wire nc1952;
wire nc1953;
wire nc1954;
wire nc1955;
wire nc1956;
wire nc1957;
wire nc1958;
wire nc1959;
wire nc1960;
wire nc1961;
wire nc1962;
wire nc1963;
wire nc1964;
wire nc1965;
wire nc1966;
wire nc1967;
wire nc1968;
wire nc1969;
wire nc1970;
wire nc1971;
wire nc1972;
wire nc1973;
wire nc1974;
wire nc1975;
wire nc1976;
wire nc1977;
wire nc1978;
wire nc1979;
wire nc1980;
wire nc1981;
wire nc1982;
wire nc1983;
wire nc1984;
wire nc1985;
wire nc1986;
wire nc1987;
wire nc1988;
wire nc1989;
wire nc1990;
wire nc1991;
wire nc1992;
wire nc1993;
wire nc1994;
wire nc1995;
wire nc1996;
wire nc1997;
wire nc1998;
wire nc1999;
wire nc2000;
wire nc2001;
wire nc2002;
wire nc2003;
wire nc2004;
wire nc2005;
wire nc2006;
wire nc2007;
wire nc2008;
wire nc2009;
wire nc2010;
wire nc2011;
wire nc2012;
wire nc2013;
wire nc2014;
wire nc2015;
wire nc2016;

assign vcc_net = 1;
assign gnd_net = 0;
EMB18K #(
		.clka_inv (1'b0),
		.clkb_inv (1'b0),
		.eccreaden (1'b0),
		.eccwriteen (1'b0),
		.emb5k_1_init_file (""),
		.emb5k_2_init_file (""),
		.emb5k_3_init_file (""),
		.emb5k_4_init_file (""),
		.extension_mode ("power"),
		.init_file ("none"),
		.outreg_a (1'b0),
		.outreg_b (1'b0),
		.rammode ("sp"),
		.use_parity (1'b0),
		.width_a (1),
		.width_b (1),
		.writemode_a ("no_change"),
		.writemode_b ("write_first")
	)
	emb_0(
		.doa({nc1, nc2, nc3, nc4, nc5, nc6, nc7, nc8, nc9, nc10, nc11, nc12, nc13, nc14, nc15, nc16, nc17, nc18, nc19, nc20, nc21, nc22, nc23, nc24, nc25, nc26, nc27, nc28, nc29, nc30, nc31, nc32, nc33, nc34, nc35, nc36, nc37, nc38, nc39, nc40, nc41, nc42, nc43, nc44, nc45, nc46, nc47, nc48, nc49, nc50, nc51, nc52, nc53, nc54, nc55, nc56, nc57, nc58, nc59, nc60, nc61, nc62, nc63, net_18}),
		.dob(),
		.dopa(),
		.dopb(),
		.addra({a[13], a[12], a[11], a[10], a[9], a[8], a[7], a[6], a[5], a[4], a[3], a[2], a[1], a[0]}),
		.addrb(),
		.clka(clk),
		.clkb(),
		.dia({nc64, nc65, nc66, nc67, nc68, nc69, nc70, nc71, nc72, nc73, nc74, nc75, nc76, nc77, nc78, nc79, nc80, nc81, nc82, nc83, nc84, nc85, nc86, nc87, nc88, nc89, nc90, nc91, nc92, nc93, nc94, nc95, nc96, nc97, nc98, nc99, nc100, nc101, nc102, nc103, nc104, nc105, nc106, nc107, nc108, nc109, nc110, nc111, nc112, nc113, nc114, nc115, nc116, nc117, nc118, nc119, nc120, nc121, nc122, nc123, nc124, nc125, nc126, d[0]}),
		.dib(),
		.dipa(),
		.dipb(),
		.cea(net_2),
		.ceb(gnd_net),
		.regcea(vcc_net),
		.regceb(),
		.regsra(rstn),
		.regsrb(),
		.wea({we, we, we, we}),
		.web(),
		.eccoutdberr(),
		.eccoutsberr(),
		.eccreadaddr(),
		.eccindberr(gnd_net),
		.eccinsberr(gnd_net)
	);EMB18K #(
		.clka_inv (1'b0),
		.clkb_inv (1'b0),
		.eccreaden (1'b0),
		.eccwriteen (1'b0),
		.emb5k_1_init_file (""),
		.emb5k_2_init_file (""),
		.emb5k_3_init_file (""),
		.emb5k_4_init_file (""),
		.extension_mode ("power"),
		.init_file ("none"),
		.outreg_a (1'b0),
		.outreg_b (1'b0),
		.rammode ("sp"),
		.use_parity (1'b0),
		.width_a (1),
		.width_b (1),
		.writemode_a ("no_change"),
		.writemode_b ("write_first")
	)
	emb_4(
		.doa({nc127, nc128, nc129, nc130, nc131, nc132, nc133, nc134, nc135, nc136, nc137, nc138, nc139, nc140, nc141, nc142, nc143, nc144, nc145, nc146, nc147, nc148, nc149, nc150, nc151, nc152, nc153, nc154, nc155, nc156, nc157, nc158, nc159, nc160, nc161, nc162, nc163, nc164, nc165, nc166, nc167, nc168, nc169, nc170, nc171, nc172, nc173, nc174, nc175, nc176, nc177, nc178, nc179, nc180, nc181, nc182, nc183, nc184, nc185, nc186, nc187, nc188, nc189, net_21}),
		.dob(),
		.dopa(),
		.dopb(),
		.addra({a[13], a[12], a[11], a[10], a[9], a[8], a[7], a[6], a[5], a[4], a[3], a[2], a[1], a[0]}),
		.addrb(),
		.clka(clk),
		.clkb(),
		.dia({nc190, nc191, nc192, nc193, nc194, nc195, nc196, nc197, nc198, nc199, nc200, nc201, nc202, nc203, nc204, nc205, nc206, nc207, nc208, nc209, nc210, nc211, nc212, nc213, nc214, nc215, nc216, nc217, nc218, nc219, nc220, nc221, nc222, nc223, nc224, nc225, nc226, nc227, nc228, nc229, nc230, nc231, nc232, nc233, nc234, nc235, nc236, nc237, nc238, nc239, nc240, nc241, nc242, nc243, nc244, nc245, nc246, nc247, nc248, nc249, nc250, nc251, nc252, d[0]}),
		.dib(),
		.dipa(),
		.dipb(),
		.cea(net_20),
		.ceb(gnd_net),
		.regcea(vcc_net),
		.regceb(),
		.regsra(rstn),
		.regsrb(),
		.wea({we, we, we, we}),
		.web(),
		.eccoutdberr(),
		.eccoutsberr(),
		.eccreadaddr(),
		.eccindberr(gnd_net),
		.eccinsberr(gnd_net)
	);NMS_ADDR_PIPE_A u_addra_pipe_14(
		.clk(clk),
		.ena(net_24),
		.i(a[14]),
		.o(addra_pipe_14_net)
	);NMS_NOT u0(
		.i(we),
		.o(net_23)
	);NMS_AND u1(
		.i0(ce),
		.i1(net_23),
		.o(net_24)
	);NMS_MUX u2(
		.sel(addra_pipe_14_net),
		.i0(net_18),
		.i1(net_21),
		.o(net_26)
	);NMS_AND u3(
		.i0(net_28),
		.i1(net_27),
		.o(net_2)
	);NMS_AND u4(
		.i0(net_28),
		.i1(a[14]),
		.o(net_20)
	);NMS_NOT u5(
		.i(a[14]),
		.o(net_27)
	);EMB18K #(
		.clka_inv (1'b0),
		.clkb_inv (1'b0),
		.eccreaden (1'b0),
		.eccwriteen (1'b0),
		.emb5k_1_init_file (""),
		.emb5k_2_init_file (""),
		.emb5k_3_init_file (""),
		.emb5k_4_init_file (""),
		.extension_mode ("power"),
		.init_file ("none"),
		.outreg_a (1'b0),
		.outreg_b (1'b0),
		.rammode ("sp"),
		.use_parity (1'b0),
		.width_a (1),
		.width_b (1),
		.writemode_a ("no_change"),
		.writemode_b ("write_first")
	)
	emb_8(
		.doa({nc253, nc254, nc255, nc256, nc257, nc258, nc259, nc260, nc261, nc262, nc263, nc264, nc265, nc266, nc267, nc268, nc269, nc270, nc271, nc272, nc273, nc274, nc275, nc276, nc277, nc278, nc279, nc280, nc281, nc282, nc283, nc284, nc285, nc286, nc287, nc288, nc289, nc290, nc291, nc292, nc293, nc294, nc295, nc296, nc297, nc298, nc299, nc300, nc301, nc302, nc303, nc304, nc305, nc306, nc307, nc308, nc309, nc310, nc311, nc312, nc313, nc314, nc315, net_30}),
		.dob(),
		.dopa(),
		.dopb(),
		.addra({a[13], a[12], a[11], a[10], a[9], a[8], a[7], a[6], a[5], a[4], a[3], a[2], a[1], a[0]}),
		.addrb(),
		.clka(clk),
		.clkb(),
		.dia({nc316, nc317, nc318, nc319, nc320, nc321, nc322, nc323, nc324, nc325, nc326, nc327, nc328, nc329, nc330, nc331, nc332, nc333, nc334, nc335, nc336, nc337, nc338, nc339, nc340, nc341, nc342, nc343, nc344, nc345, nc346, nc347, nc348, nc349, nc350, nc351, nc352, nc353, nc354, nc355, nc356, nc357, nc358, nc359, nc360, nc361, nc362, nc363, nc364, nc365, nc366, nc367, nc368, nc369, nc370, nc371, nc372, nc373, nc374, nc375, nc376, nc377, nc378, d[0]}),
		.dib(),
		.dipa(),
		.dipb(),
		.cea(net_29),
		.ceb(gnd_net),
		.regcea(vcc_net),
		.regceb(),
		.regsra(rstn),
		.regsrb(),
		.wea({we, we, we, we}),
		.web(),
		.eccoutdberr(),
		.eccoutsberr(),
		.eccreadaddr(),
		.eccindberr(gnd_net),
		.eccinsberr(gnd_net)
	);EMB18K #(
		.clka_inv (1'b0),
		.clkb_inv (1'b0),
		.eccreaden (1'b0),
		.eccwriteen (1'b0),
		.emb5k_1_init_file (""),
		.emb5k_2_init_file (""),
		.emb5k_3_init_file (""),
		.emb5k_4_init_file (""),
		.extension_mode ("power"),
		.init_file ("none"),
		.outreg_a (1'b0),
		.outreg_b (1'b0),
		.rammode ("sp"),
		.use_parity (1'b0),
		.width_a (1),
		.width_b (1),
		.writemode_a ("no_change"),
		.writemode_b ("write_first")
	)
	emb_12(
		.doa({nc379, nc380, nc381, nc382, nc383, nc384, nc385, nc386, nc387, nc388, nc389, nc390, nc391, nc392, nc393, nc394, nc395, nc396, nc397, nc398, nc399, nc400, nc401, nc402, nc403, nc404, nc405, nc406, nc407, nc408, nc409, nc410, nc411, nc412, nc413, nc414, nc415, nc416, nc417, nc418, nc419, nc420, nc421, nc422, nc423, nc424, nc425, nc426, nc427, nc428, nc429, nc430, nc431, nc432, nc433, nc434, nc435, nc436, nc437, nc438, nc439, nc440, nc441, net_32}),
		.dob(),
		.dopa(),
		.dopb(),
		.addra({a[13], a[12], a[11], a[10], a[9], a[8], a[7], a[6], a[5], a[4], a[3], a[2], a[1], a[0]}),
		.addrb(),
		.clka(clk),
		.clkb(),
		.dia({nc442, nc443, nc444, nc445, nc446, nc447, nc448, nc449, nc450, nc451, nc452, nc453, nc454, nc455, nc456, nc457, nc458, nc459, nc460, nc461, nc462, nc463, nc464, nc465, nc466, nc467, nc468, nc469, nc470, nc471, nc472, nc473, nc474, nc475, nc476, nc477, nc478, nc479, nc480, nc481, nc482, nc483, nc484, nc485, nc486, nc487, nc488, nc489, nc490, nc491, nc492, nc493, nc494, nc495, nc496, nc497, nc498, nc499, nc500, nc501, nc502, nc503, nc504, d[0]}),
		.dib(),
		.dipa(),
		.dipb(),
		.cea(net_31),
		.ceb(gnd_net),
		.regcea(vcc_net),
		.regceb(),
		.regsra(rstn),
		.regsrb(),
		.wea({we, we, we, we}),
		.web(),
		.eccoutdberr(),
		.eccoutsberr(),
		.eccreadaddr(),
		.eccindberr(gnd_net),
		.eccinsberr(gnd_net)
	);NMS_MUX u6(
		.sel(addra_pipe_14_net),
		.i0(net_30),
		.i1(net_32),
		.o(net_33)
	);NMS_AND u7(
		.i0(net_35),
		.i1(net_34),
		.o(net_29)
	);NMS_AND u8(
		.i0(net_35),
		.i1(a[14]),
		.o(net_31)
	);NMS_NOT u9(
		.i(a[14]),
		.o(net_34)
	);NMS_ADDR_PIPE_A u_addra_pipe_15(
		.clk(clk),
		.ena(net_37),
		.i(a[15]),
		.o(addra_pipe_15_net)
	);NMS_NOT u10(
		.i(we),
		.o(net_36)
	);NMS_AND u11(
		.i0(ce),
		.i1(net_36),
		.o(net_37)
	);NMS_MUX u12(
		.sel(addra_pipe_15_net),
		.i0(net_26),
		.i1(net_33),
		.o(net_39)
	);NMS_AND u13(
		.i0(net_41),
		.i1(net_40),
		.o(net_28)
	);NMS_AND u14(
		.i0(net_41),
		.i1(a[15]),
		.o(net_35)
	);NMS_NOT u15(
		.i(a[15]),
		.o(net_40)
	);EMB18K #(
		.clka_inv (1'b0),
		.clkb_inv (1'b0),
		.eccreaden (1'b0),
		.eccwriteen (1'b0),
		.emb5k_1_init_file (""),
		.emb5k_2_init_file (""),
		.emb5k_3_init_file (""),
		.emb5k_4_init_file (""),
		.extension_mode ("power"),
		.init_file ("none"),
		.outreg_a (1'b0),
		.outreg_b (1'b0),
		.rammode ("sp"),
		.use_parity (1'b0),
		.width_a (1),
		.width_b (1),
		.writemode_a ("no_change"),
		.writemode_b ("write_first")
	)
	emb_16(
		.doa({nc505, nc506, nc507, nc508, nc509, nc510, nc511, nc512, nc513, nc514, nc515, nc516, nc517, nc518, nc519, nc520, nc521, nc522, nc523, nc524, nc525, nc526, nc527, nc528, nc529, nc530, nc531, nc532, nc533, nc534, nc535, nc536, nc537, nc538, nc539, nc540, nc541, nc542, nc543, nc544, nc545, nc546, nc547, nc548, nc549, nc550, nc551, nc552, nc553, nc554, nc555, nc556, nc557, nc558, nc559, nc560, nc561, nc562, nc563, nc564, nc565, nc566, nc567, net_43}),
		.dob(),
		.dopa(),
		.dopb(),
		.addra({a[13], a[12], a[11], a[10], a[9], a[8], a[7], a[6], a[5], a[4], a[3], a[2], a[1], a[0]}),
		.addrb(),
		.clka(clk),
		.clkb(),
		.dia({nc568, nc569, nc570, nc571, nc572, nc573, nc574, nc575, nc576, nc577, nc578, nc579, nc580, nc581, nc582, nc583, nc584, nc585, nc586, nc587, nc588, nc589, nc590, nc591, nc592, nc593, nc594, nc595, nc596, nc597, nc598, nc599, nc600, nc601, nc602, nc603, nc604, nc605, nc606, nc607, nc608, nc609, nc610, nc611, nc612, nc613, nc614, nc615, nc616, nc617, nc618, nc619, nc620, nc621, nc622, nc623, nc624, nc625, nc626, nc627, nc628, nc629, nc630, d[0]}),
		.dib(),
		.dipa(),
		.dipb(),
		.cea(net_42),
		.ceb(gnd_net),
		.regcea(vcc_net),
		.regceb(),
		.regsra(rstn),
		.regsrb(),
		.wea({we, we, we, we}),
		.web(),
		.eccoutdberr(),
		.eccoutsberr(),
		.eccreadaddr(),
		.eccindberr(gnd_net),
		.eccinsberr(gnd_net)
	);EMB18K #(
		.clka_inv (1'b0),
		.clkb_inv (1'b0),
		.eccreaden (1'b0),
		.eccwriteen (1'b0),
		.emb5k_1_init_file (""),
		.emb5k_2_init_file (""),
		.emb5k_3_init_file (""),
		.emb5k_4_init_file (""),
		.extension_mode ("power"),
		.init_file ("none"),
		.outreg_a (1'b0),
		.outreg_b (1'b0),
		.rammode ("sp"),
		.use_parity (1'b0),
		.width_a (1),
		.width_b (1),
		.writemode_a ("no_change"),
		.writemode_b ("write_first")
	)
	emb_20(
		.doa({nc631, nc632, nc633, nc634, nc635, nc636, nc637, nc638, nc639, nc640, nc641, nc642, nc643, nc644, nc645, nc646, nc647, nc648, nc649, nc650, nc651, nc652, nc653, nc654, nc655, nc656, nc657, nc658, nc659, nc660, nc661, nc662, nc663, nc664, nc665, nc666, nc667, nc668, nc669, nc670, nc671, nc672, nc673, nc674, nc675, nc676, nc677, nc678, nc679, nc680, nc681, nc682, nc683, nc684, nc685, nc686, nc687, nc688, nc689, nc690, nc691, nc692, nc693, net_45}),
		.dob(),
		.dopa(),
		.dopb(),
		.addra({a[13], a[12], a[11], a[10], a[9], a[8], a[7], a[6], a[5], a[4], a[3], a[2], a[1], a[0]}),
		.addrb(),
		.clka(clk),
		.clkb(),
		.dia({nc694, nc695, nc696, nc697, nc698, nc699, nc700, nc701, nc702, nc703, nc704, nc705, nc706, nc707, nc708, nc709, nc710, nc711, nc712, nc713, nc714, nc715, nc716, nc717, nc718, nc719, nc720, nc721, nc722, nc723, nc724, nc725, nc726, nc727, nc728, nc729, nc730, nc731, nc732, nc733, nc734, nc735, nc736, nc737, nc738, nc739, nc740, nc741, nc742, nc743, nc744, nc745, nc746, nc747, nc748, nc749, nc750, nc751, nc752, nc753, nc754, nc755, nc756, d[0]}),
		.dib(),
		.dipa(),
		.dipb(),
		.cea(net_44),
		.ceb(gnd_net),
		.regcea(vcc_net),
		.regceb(),
		.regsra(rstn),
		.regsrb(),
		.wea({we, we, we, we}),
		.web(),
		.eccoutdberr(),
		.eccoutsberr(),
		.eccreadaddr(),
		.eccindberr(gnd_net),
		.eccinsberr(gnd_net)
	);NMS_MUX u16(
		.sel(addra_pipe_14_net),
		.i0(net_43),
		.i1(net_45),
		.o(net_46)
	);NMS_AND u17(
		.i0(net_48),
		.i1(net_47),
		.o(net_42)
	);NMS_AND u18(
		.i0(net_48),
		.i1(a[14]),
		.o(net_44)
	);NMS_NOT u19(
		.i(a[14]),
		.o(net_47)
	);EMB18K #(
		.clka_inv (1'b0),
		.clkb_inv (1'b0),
		.eccreaden (1'b0),
		.eccwriteen (1'b0),
		.emb5k_1_init_file (""),
		.emb5k_2_init_file (""),
		.emb5k_3_init_file (""),
		.emb5k_4_init_file (""),
		.extension_mode ("power"),
		.init_file ("none"),
		.outreg_a (1'b0),
		.outreg_b (1'b0),
		.rammode ("sp"),
		.use_parity (1'b0),
		.width_a (1),
		.width_b (1),
		.writemode_a ("no_change"),
		.writemode_b ("write_first")
	)
	emb_24(
		.doa({nc757, nc758, nc759, nc760, nc761, nc762, nc763, nc764, nc765, nc766, nc767, nc768, nc769, nc770, nc771, nc772, nc773, nc774, nc775, nc776, nc777, nc778, nc779, nc780, nc781, nc782, nc783, nc784, nc785, nc786, nc787, nc788, nc789, nc790, nc791, nc792, nc793, nc794, nc795, nc796, nc797, nc798, nc799, nc800, nc801, nc802, nc803, nc804, nc805, nc806, nc807, nc808, nc809, nc810, nc811, nc812, nc813, nc814, nc815, nc816, nc817, nc818, nc819, net_50}),
		.dob(),
		.dopa(),
		.dopb(),
		.addra({a[13], a[12], a[11], a[10], a[9], a[8], a[7], a[6], a[5], a[4], a[3], a[2], a[1], a[0]}),
		.addrb(),
		.clka(clk),
		.clkb(),
		.dia({nc820, nc821, nc822, nc823, nc824, nc825, nc826, nc827, nc828, nc829, nc830, nc831, nc832, nc833, nc834, nc835, nc836, nc837, nc838, nc839, nc840, nc841, nc842, nc843, nc844, nc845, nc846, nc847, nc848, nc849, nc850, nc851, nc852, nc853, nc854, nc855, nc856, nc857, nc858, nc859, nc860, nc861, nc862, nc863, nc864, nc865, nc866, nc867, nc868, nc869, nc870, nc871, nc872, nc873, nc874, nc875, nc876, nc877, nc878, nc879, nc880, nc881, nc882, d[0]}),
		.dib(),
		.dipa(),
		.dipb(),
		.cea(net_49),
		.ceb(gnd_net),
		.regcea(vcc_net),
		.regceb(),
		.regsra(rstn),
		.regsrb(),
		.wea({we, we, we, we}),
		.web(),
		.eccoutdberr(),
		.eccoutsberr(),
		.eccreadaddr(),
		.eccindberr(gnd_net),
		.eccinsberr(gnd_net)
	);EMB18K #(
		.clka_inv (1'b0),
		.clkb_inv (1'b0),
		.eccreaden (1'b0),
		.eccwriteen (1'b0),
		.emb5k_1_init_file (""),
		.emb5k_2_init_file (""),
		.emb5k_3_init_file (""),
		.emb5k_4_init_file (""),
		.extension_mode ("power"),
		.init_file ("none"),
		.outreg_a (1'b0),
		.outreg_b (1'b0),
		.rammode ("sp"),
		.use_parity (1'b0),
		.width_a (1),
		.width_b (1),
		.writemode_a ("no_change"),
		.writemode_b ("write_first")
	)
	emb_28(
		.doa({nc883, nc884, nc885, nc886, nc887, nc888, nc889, nc890, nc891, nc892, nc893, nc894, nc895, nc896, nc897, nc898, nc899, nc900, nc901, nc902, nc903, nc904, nc905, nc906, nc907, nc908, nc909, nc910, nc911, nc912, nc913, nc914, nc915, nc916, nc917, nc918, nc919, nc920, nc921, nc922, nc923, nc924, nc925, nc926, nc927, nc928, nc929, nc930, nc931, nc932, nc933, nc934, nc935, nc936, nc937, nc938, nc939, nc940, nc941, nc942, nc943, nc944, nc945, net_52}),
		.dob(),
		.dopa(),
		.dopb(),
		.addra({a[13], a[12], a[11], a[10], a[9], a[8], a[7], a[6], a[5], a[4], a[3], a[2], a[1], a[0]}),
		.addrb(),
		.clka(clk),
		.clkb(),
		.dia({nc946, nc947, nc948, nc949, nc950, nc951, nc952, nc953, nc954, nc955, nc956, nc957, nc958, nc959, nc960, nc961, nc962, nc963, nc964, nc965, nc966, nc967, nc968, nc969, nc970, nc971, nc972, nc973, nc974, nc975, nc976, nc977, nc978, nc979, nc980, nc981, nc982, nc983, nc984, nc985, nc986, nc987, nc988, nc989, nc990, nc991, nc992, nc993, nc994, nc995, nc996, nc997, nc998, nc999, nc1000, nc1001, nc1002, nc1003, nc1004, nc1005, nc1006, nc1007, nc1008, d[0]}),
		.dib(),
		.dipa(),
		.dipb(),
		.cea(net_51),
		.ceb(gnd_net),
		.regcea(vcc_net),
		.regceb(),
		.regsra(rstn),
		.regsrb(),
		.wea({we, we, we, we}),
		.web(),
		.eccoutdberr(),
		.eccoutsberr(),
		.eccreadaddr(),
		.eccindberr(gnd_net),
		.eccinsberr(gnd_net)
	);NMS_MUX u20(
		.sel(addra_pipe_14_net),
		.i0(net_50),
		.i1(net_52),
		.o(net_53)
	);NMS_AND u21(
		.i0(net_55),
		.i1(net_54),
		.o(net_49)
	);NMS_AND u22(
		.i0(net_55),
		.i1(a[14]),
		.o(net_51)
	);NMS_NOT u23(
		.i(a[14]),
		.o(net_54)
	);NMS_MUX u24(
		.sel(addra_pipe_15_net),
		.i0(net_46),
		.i1(net_53),
		.o(net_56)
	);NMS_AND u25(
		.i0(net_58),
		.i1(net_57),
		.o(net_48)
	);NMS_AND u26(
		.i0(net_58),
		.i1(a[15]),
		.o(net_55)
	);NMS_NOT u27(
		.i(a[15]),
		.o(net_57)
	);NMS_ADDR_PIPE_A u_addra_pipe_16(
		.clk(clk),
		.ena(net_60),
		.i(a[16]),
		.o(addra_pipe_16_net)
	);NMS_NOT u28(
		.i(we),
		.o(net_59)
	);NMS_AND u29(
		.i0(ce),
		.i1(net_59),
		.o(net_60)
	);NMS_MUX u30(
		.sel(addra_pipe_16_net),
		.i0(net_39),
		.i1(net_56),
		.o(net_62)
	);NMS_AND u31(
		.i0(net_64),
		.i1(net_63),
		.o(net_41)
	);NMS_AND u32(
		.i0(net_64),
		.i1(a[16]),
		.o(net_58)
	);NMS_NOT u33(
		.i(a[16]),
		.o(net_63)
	);EMB18K #(
		.clka_inv (1'b0),
		.clkb_inv (1'b0),
		.eccreaden (1'b0),
		.eccwriteen (1'b0),
		.emb5k_1_init_file (""),
		.emb5k_2_init_file (""),
		.emb5k_3_init_file (""),
		.emb5k_4_init_file (""),
		.extension_mode ("power"),
		.init_file ("none"),
		.outreg_a (1'b0),
		.outreg_b (1'b0),
		.rammode ("sp"),
		.use_parity (1'b0),
		.width_a (1),
		.width_b (1),
		.writemode_a ("no_change"),
		.writemode_b ("write_first")
	)
	emb_32(
		.doa({nc1009, nc1010, nc1011, nc1012, nc1013, nc1014, nc1015, nc1016, nc1017, nc1018, nc1019, nc1020, nc1021, nc1022, nc1023, nc1024, nc1025, nc1026, nc1027, nc1028, nc1029, nc1030, nc1031, nc1032, nc1033, nc1034, nc1035, nc1036, nc1037, nc1038, nc1039, nc1040, nc1041, nc1042, nc1043, nc1044, nc1045, nc1046, nc1047, nc1048, nc1049, nc1050, nc1051, nc1052, nc1053, nc1054, nc1055, nc1056, nc1057, nc1058, nc1059, nc1060, nc1061, nc1062, nc1063, nc1064, nc1065, nc1066, nc1067, nc1068, nc1069, nc1070, nc1071, net_66}),
		.dob(),
		.dopa(),
		.dopb(),
		.addra({a[13], a[12], a[11], a[10], a[9], a[8], a[7], a[6], a[5], a[4], a[3], a[2], a[1], a[0]}),
		.addrb(),
		.clka(clk),
		.clkb(),
		.dia({nc1072, nc1073, nc1074, nc1075, nc1076, nc1077, nc1078, nc1079, nc1080, nc1081, nc1082, nc1083, nc1084, nc1085, nc1086, nc1087, nc1088, nc1089, nc1090, nc1091, nc1092, nc1093, nc1094, nc1095, nc1096, nc1097, nc1098, nc1099, nc1100, nc1101, nc1102, nc1103, nc1104, nc1105, nc1106, nc1107, nc1108, nc1109, nc1110, nc1111, nc1112, nc1113, nc1114, nc1115, nc1116, nc1117, nc1118, nc1119, nc1120, nc1121, nc1122, nc1123, nc1124, nc1125, nc1126, nc1127, nc1128, nc1129, nc1130, nc1131, nc1132, nc1133, nc1134, d[0]}),
		.dib(),
		.dipa(),
		.dipb(),
		.cea(net_65),
		.ceb(gnd_net),
		.regcea(vcc_net),
		.regceb(),
		.regsra(rstn),
		.regsrb(),
		.wea({we, we, we, we}),
		.web(),
		.eccoutdberr(),
		.eccoutsberr(),
		.eccreadaddr(),
		.eccindberr(gnd_net),
		.eccinsberr(gnd_net)
	);EMB18K #(
		.clka_inv (1'b0),
		.clkb_inv (1'b0),
		.eccreaden (1'b0),
		.eccwriteen (1'b0),
		.emb5k_1_init_file (""),
		.emb5k_2_init_file (""),
		.emb5k_3_init_file (""),
		.emb5k_4_init_file (""),
		.extension_mode ("power"),
		.init_file ("none"),
		.outreg_a (1'b0),
		.outreg_b (1'b0),
		.rammode ("sp"),
		.use_parity (1'b0),
		.width_a (1),
		.width_b (1),
		.writemode_a ("no_change"),
		.writemode_b ("write_first")
	)
	emb_36(
		.doa({nc1135, nc1136, nc1137, nc1138, nc1139, nc1140, nc1141, nc1142, nc1143, nc1144, nc1145, nc1146, nc1147, nc1148, nc1149, nc1150, nc1151, nc1152, nc1153, nc1154, nc1155, nc1156, nc1157, nc1158, nc1159, nc1160, nc1161, nc1162, nc1163, nc1164, nc1165, nc1166, nc1167, nc1168, nc1169, nc1170, nc1171, nc1172, nc1173, nc1174, nc1175, nc1176, nc1177, nc1178, nc1179, nc1180, nc1181, nc1182, nc1183, nc1184, nc1185, nc1186, nc1187, nc1188, nc1189, nc1190, nc1191, nc1192, nc1193, nc1194, nc1195, nc1196, nc1197, net_68}),
		.dob(),
		.dopa(),
		.dopb(),
		.addra({a[13], a[12], a[11], a[10], a[9], a[8], a[7], a[6], a[5], a[4], a[3], a[2], a[1], a[0]}),
		.addrb(),
		.clka(clk),
		.clkb(),
		.dia({nc1198, nc1199, nc1200, nc1201, nc1202, nc1203, nc1204, nc1205, nc1206, nc1207, nc1208, nc1209, nc1210, nc1211, nc1212, nc1213, nc1214, nc1215, nc1216, nc1217, nc1218, nc1219, nc1220, nc1221, nc1222, nc1223, nc1224, nc1225, nc1226, nc1227, nc1228, nc1229, nc1230, nc1231, nc1232, nc1233, nc1234, nc1235, nc1236, nc1237, nc1238, nc1239, nc1240, nc1241, nc1242, nc1243, nc1244, nc1245, nc1246, nc1247, nc1248, nc1249, nc1250, nc1251, nc1252, nc1253, nc1254, nc1255, nc1256, nc1257, nc1258, nc1259, nc1260, d[0]}),
		.dib(),
		.dipa(),
		.dipb(),
		.cea(net_67),
		.ceb(gnd_net),
		.regcea(vcc_net),
		.regceb(),
		.regsra(rstn),
		.regsrb(),
		.wea({we, we, we, we}),
		.web(),
		.eccoutdberr(),
		.eccoutsberr(),
		.eccreadaddr(),
		.eccindberr(gnd_net),
		.eccinsberr(gnd_net)
	);NMS_MUX u34(
		.sel(addra_pipe_14_net),
		.i0(net_66),
		.i1(net_68),
		.o(net_69)
	);NMS_AND u35(
		.i0(net_71),
		.i1(net_70),
		.o(net_65)
	);NMS_AND u36(
		.i0(net_71),
		.i1(a[14]),
		.o(net_67)
	);NMS_NOT u37(
		.i(a[14]),
		.o(net_70)
	);EMB18K #(
		.clka_inv (1'b0),
		.clkb_inv (1'b0),
		.eccreaden (1'b0),
		.eccwriteen (1'b0),
		.emb5k_1_init_file (""),
		.emb5k_2_init_file (""),
		.emb5k_3_init_file (""),
		.emb5k_4_init_file (""),
		.extension_mode ("power"),
		.init_file ("none"),
		.outreg_a (1'b0),
		.outreg_b (1'b0),
		.rammode ("sp"),
		.use_parity (1'b0),
		.width_a (1),
		.width_b (1),
		.writemode_a ("no_change"),
		.writemode_b ("write_first")
	)
	emb_40(
		.doa({nc1261, nc1262, nc1263, nc1264, nc1265, nc1266, nc1267, nc1268, nc1269, nc1270, nc1271, nc1272, nc1273, nc1274, nc1275, nc1276, nc1277, nc1278, nc1279, nc1280, nc1281, nc1282, nc1283, nc1284, nc1285, nc1286, nc1287, nc1288, nc1289, nc1290, nc1291, nc1292, nc1293, nc1294, nc1295, nc1296, nc1297, nc1298, nc1299, nc1300, nc1301, nc1302, nc1303, nc1304, nc1305, nc1306, nc1307, nc1308, nc1309, nc1310, nc1311, nc1312, nc1313, nc1314, nc1315, nc1316, nc1317, nc1318, nc1319, nc1320, nc1321, nc1322, nc1323, net_73}),
		.dob(),
		.dopa(),
		.dopb(),
		.addra({a[13], a[12], a[11], a[10], a[9], a[8], a[7], a[6], a[5], a[4], a[3], a[2], a[1], a[0]}),
		.addrb(),
		.clka(clk),
		.clkb(),
		.dia({nc1324, nc1325, nc1326, nc1327, nc1328, nc1329, nc1330, nc1331, nc1332, nc1333, nc1334, nc1335, nc1336, nc1337, nc1338, nc1339, nc1340, nc1341, nc1342, nc1343, nc1344, nc1345, nc1346, nc1347, nc1348, nc1349, nc1350, nc1351, nc1352, nc1353, nc1354, nc1355, nc1356, nc1357, nc1358, nc1359, nc1360, nc1361, nc1362, nc1363, nc1364, nc1365, nc1366, nc1367, nc1368, nc1369, nc1370, nc1371, nc1372, nc1373, nc1374, nc1375, nc1376, nc1377, nc1378, nc1379, nc1380, nc1381, nc1382, nc1383, nc1384, nc1385, nc1386, d[0]}),
		.dib(),
		.dipa(),
		.dipb(),
		.cea(net_72),
		.ceb(gnd_net),
		.regcea(vcc_net),
		.regceb(),
		.regsra(rstn),
		.regsrb(),
		.wea({we, we, we, we}),
		.web(),
		.eccoutdberr(),
		.eccoutsberr(),
		.eccreadaddr(),
		.eccindberr(gnd_net),
		.eccinsberr(gnd_net)
	);EMB18K #(
		.clka_inv (1'b0),
		.clkb_inv (1'b0),
		.eccreaden (1'b0),
		.eccwriteen (1'b0),
		.emb5k_1_init_file (""),
		.emb5k_2_init_file (""),
		.emb5k_3_init_file (""),
		.emb5k_4_init_file (""),
		.extension_mode ("power"),
		.init_file ("none"),
		.outreg_a (1'b0),
		.outreg_b (1'b0),
		.rammode ("sp"),
		.use_parity (1'b0),
		.width_a (1),
		.width_b (1),
		.writemode_a ("no_change"),
		.writemode_b ("write_first")
	)
	emb_44(
		.doa({nc1387, nc1388, nc1389, nc1390, nc1391, nc1392, nc1393, nc1394, nc1395, nc1396, nc1397, nc1398, nc1399, nc1400, nc1401, nc1402, nc1403, nc1404, nc1405, nc1406, nc1407, nc1408, nc1409, nc1410, nc1411, nc1412, nc1413, nc1414, nc1415, nc1416, nc1417, nc1418, nc1419, nc1420, nc1421, nc1422, nc1423, nc1424, nc1425, nc1426, nc1427, nc1428, nc1429, nc1430, nc1431, nc1432, nc1433, nc1434, nc1435, nc1436, nc1437, nc1438, nc1439, nc1440, nc1441, nc1442, nc1443, nc1444, nc1445, nc1446, nc1447, nc1448, nc1449, net_75}),
		.dob(),
		.dopa(),
		.dopb(),
		.addra({a[13], a[12], a[11], a[10], a[9], a[8], a[7], a[6], a[5], a[4], a[3], a[2], a[1], a[0]}),
		.addrb(),
		.clka(clk),
		.clkb(),
		.dia({nc1450, nc1451, nc1452, nc1453, nc1454, nc1455, nc1456, nc1457, nc1458, nc1459, nc1460, nc1461, nc1462, nc1463, nc1464, nc1465, nc1466, nc1467, nc1468, nc1469, nc1470, nc1471, nc1472, nc1473, nc1474, nc1475, nc1476, nc1477, nc1478, nc1479, nc1480, nc1481, nc1482, nc1483, nc1484, nc1485, nc1486, nc1487, nc1488, nc1489, nc1490, nc1491, nc1492, nc1493, nc1494, nc1495, nc1496, nc1497, nc1498, nc1499, nc1500, nc1501, nc1502, nc1503, nc1504, nc1505, nc1506, nc1507, nc1508, nc1509, nc1510, nc1511, nc1512, d[0]}),
		.dib(),
		.dipa(),
		.dipb(),
		.cea(net_74),
		.ceb(gnd_net),
		.regcea(vcc_net),
		.regceb(),
		.regsra(rstn),
		.regsrb(),
		.wea({we, we, we, we}),
		.web(),
		.eccoutdberr(),
		.eccoutsberr(),
		.eccreadaddr(),
		.eccindberr(gnd_net),
		.eccinsberr(gnd_net)
	);NMS_MUX u38(
		.sel(addra_pipe_14_net),
		.i0(net_73),
		.i1(net_75),
		.o(net_76)
	);NMS_AND u39(
		.i0(net_78),
		.i1(net_77),
		.o(net_72)
	);NMS_AND u40(
		.i0(net_78),
		.i1(a[14]),
		.o(net_74)
	);NMS_NOT u41(
		.i(a[14]),
		.o(net_77)
	);NMS_MUX u42(
		.sel(addra_pipe_15_net),
		.i0(net_69),
		.i1(net_76),
		.o(net_79)
	);NMS_AND u43(
		.i0(net_81),
		.i1(net_80),
		.o(net_71)
	);NMS_AND u44(
		.i0(net_81),
		.i1(a[15]),
		.o(net_78)
	);NMS_NOT u45(
		.i(a[15]),
		.o(net_80)
	);EMB18K #(
		.clka_inv (1'b0),
		.clkb_inv (1'b0),
		.eccreaden (1'b0),
		.eccwriteen (1'b0),
		.emb5k_1_init_file (""),
		.emb5k_2_init_file (""),
		.emb5k_3_init_file (""),
		.emb5k_4_init_file (""),
		.extension_mode ("power"),
		.init_file ("none"),
		.outreg_a (1'b0),
		.outreg_b (1'b0),
		.rammode ("sp"),
		.use_parity (1'b0),
		.width_a (1),
		.width_b (1),
		.writemode_a ("no_change"),
		.writemode_b ("write_first")
	)
	emb_48(
		.doa({nc1513, nc1514, nc1515, nc1516, nc1517, nc1518, nc1519, nc1520, nc1521, nc1522, nc1523, nc1524, nc1525, nc1526, nc1527, nc1528, nc1529, nc1530, nc1531, nc1532, nc1533, nc1534, nc1535, nc1536, nc1537, nc1538, nc1539, nc1540, nc1541, nc1542, nc1543, nc1544, nc1545, nc1546, nc1547, nc1548, nc1549, nc1550, nc1551, nc1552, nc1553, nc1554, nc1555, nc1556, nc1557, nc1558, nc1559, nc1560, nc1561, nc1562, nc1563, nc1564, nc1565, nc1566, nc1567, nc1568, nc1569, nc1570, nc1571, nc1572, nc1573, nc1574, nc1575, net_83}),
		.dob(),
		.dopa(),
		.dopb(),
		.addra({a[13], a[12], a[11], a[10], a[9], a[8], a[7], a[6], a[5], a[4], a[3], a[2], a[1], a[0]}),
		.addrb(),
		.clka(clk),
		.clkb(),
		.dia({nc1576, nc1577, nc1578, nc1579, nc1580, nc1581, nc1582, nc1583, nc1584, nc1585, nc1586, nc1587, nc1588, nc1589, nc1590, nc1591, nc1592, nc1593, nc1594, nc1595, nc1596, nc1597, nc1598, nc1599, nc1600, nc1601, nc1602, nc1603, nc1604, nc1605, nc1606, nc1607, nc1608, nc1609, nc1610, nc1611, nc1612, nc1613, nc1614, nc1615, nc1616, nc1617, nc1618, nc1619, nc1620, nc1621, nc1622, nc1623, nc1624, nc1625, nc1626, nc1627, nc1628, nc1629, nc1630, nc1631, nc1632, nc1633, nc1634, nc1635, nc1636, nc1637, nc1638, d[0]}),
		.dib(),
		.dipa(),
		.dipb(),
		.cea(net_82),
		.ceb(gnd_net),
		.regcea(vcc_net),
		.regceb(),
		.regsra(rstn),
		.regsrb(),
		.wea({we, we, we, we}),
		.web(),
		.eccoutdberr(),
		.eccoutsberr(),
		.eccreadaddr(),
		.eccindberr(gnd_net),
		.eccinsberr(gnd_net)
	);EMB18K #(
		.clka_inv (1'b0),
		.clkb_inv (1'b0),
		.eccreaden (1'b0),
		.eccwriteen (1'b0),
		.emb5k_1_init_file (""),
		.emb5k_2_init_file (""),
		.emb5k_3_init_file (""),
		.emb5k_4_init_file (""),
		.extension_mode ("power"),
		.init_file ("none"),
		.outreg_a (1'b0),
		.outreg_b (1'b0),
		.rammode ("sp"),
		.use_parity (1'b0),
		.width_a (1),
		.width_b (1),
		.writemode_a ("no_change"),
		.writemode_b ("write_first")
	)
	emb_52(
		.doa({nc1639, nc1640, nc1641, nc1642, nc1643, nc1644, nc1645, nc1646, nc1647, nc1648, nc1649, nc1650, nc1651, nc1652, nc1653, nc1654, nc1655, nc1656, nc1657, nc1658, nc1659, nc1660, nc1661, nc1662, nc1663, nc1664, nc1665, nc1666, nc1667, nc1668, nc1669, nc1670, nc1671, nc1672, nc1673, nc1674, nc1675, nc1676, nc1677, nc1678, nc1679, nc1680, nc1681, nc1682, nc1683, nc1684, nc1685, nc1686, nc1687, nc1688, nc1689, nc1690, nc1691, nc1692, nc1693, nc1694, nc1695, nc1696, nc1697, nc1698, nc1699, nc1700, nc1701, net_85}),
		.dob(),
		.dopa(),
		.dopb(),
		.addra({a[13], a[12], a[11], a[10], a[9], a[8], a[7], a[6], a[5], a[4], a[3], a[2], a[1], a[0]}),
		.addrb(),
		.clka(clk),
		.clkb(),
		.dia({nc1702, nc1703, nc1704, nc1705, nc1706, nc1707, nc1708, nc1709, nc1710, nc1711, nc1712, nc1713, nc1714, nc1715, nc1716, nc1717, nc1718, nc1719, nc1720, nc1721, nc1722, nc1723, nc1724, nc1725, nc1726, nc1727, nc1728, nc1729, nc1730, nc1731, nc1732, nc1733, nc1734, nc1735, nc1736, nc1737, nc1738, nc1739, nc1740, nc1741, nc1742, nc1743, nc1744, nc1745, nc1746, nc1747, nc1748, nc1749, nc1750, nc1751, nc1752, nc1753, nc1754, nc1755, nc1756, nc1757, nc1758, nc1759, nc1760, nc1761, nc1762, nc1763, nc1764, d[0]}),
		.dib(),
		.dipa(),
		.dipb(),
		.cea(net_84),
		.ceb(gnd_net),
		.regcea(vcc_net),
		.regceb(),
		.regsra(rstn),
		.regsrb(),
		.wea({we, we, we, we}),
		.web(),
		.eccoutdberr(),
		.eccoutsberr(),
		.eccreadaddr(),
		.eccindberr(gnd_net),
		.eccinsberr(gnd_net)
	);NMS_MUX u46(
		.sel(addra_pipe_14_net),
		.i0(net_83),
		.i1(net_85),
		.o(net_86)
	);NMS_AND u47(
		.i0(net_88),
		.i1(net_87),
		.o(net_82)
	);NMS_AND u48(
		.i0(net_88),
		.i1(a[14]),
		.o(net_84)
	);NMS_NOT u49(
		.i(a[14]),
		.o(net_87)
	);EMB18K #(
		.clka_inv (1'b0),
		.clkb_inv (1'b0),
		.eccreaden (1'b0),
		.eccwriteen (1'b0),
		.emb5k_1_init_file (""),
		.emb5k_2_init_file (""),
		.emb5k_3_init_file (""),
		.emb5k_4_init_file (""),
		.extension_mode ("power"),
		.init_file ("none"),
		.outreg_a (1'b0),
		.outreg_b (1'b0),
		.rammode ("sp"),
		.use_parity (1'b0),
		.width_a (1),
		.width_b (1),
		.writemode_a ("no_change"),
		.writemode_b ("write_first")
	)
	emb_56(
		.doa({nc1765, nc1766, nc1767, nc1768, nc1769, nc1770, nc1771, nc1772, nc1773, nc1774, nc1775, nc1776, nc1777, nc1778, nc1779, nc1780, nc1781, nc1782, nc1783, nc1784, nc1785, nc1786, nc1787, nc1788, nc1789, nc1790, nc1791, nc1792, nc1793, nc1794, nc1795, nc1796, nc1797, nc1798, nc1799, nc1800, nc1801, nc1802, nc1803, nc1804, nc1805, nc1806, nc1807, nc1808, nc1809, nc1810, nc1811, nc1812, nc1813, nc1814, nc1815, nc1816, nc1817, nc1818, nc1819, nc1820, nc1821, nc1822, nc1823, nc1824, nc1825, nc1826, nc1827, net_90}),
		.dob(),
		.dopa(),
		.dopb(),
		.addra({a[13], a[12], a[11], a[10], a[9], a[8], a[7], a[6], a[5], a[4], a[3], a[2], a[1], a[0]}),
		.addrb(),
		.clka(clk),
		.clkb(),
		.dia({nc1828, nc1829, nc1830, nc1831, nc1832, nc1833, nc1834, nc1835, nc1836, nc1837, nc1838, nc1839, nc1840, nc1841, nc1842, nc1843, nc1844, nc1845, nc1846, nc1847, nc1848, nc1849, nc1850, nc1851, nc1852, nc1853, nc1854, nc1855, nc1856, nc1857, nc1858, nc1859, nc1860, nc1861, nc1862, nc1863, nc1864, nc1865, nc1866, nc1867, nc1868, nc1869, nc1870, nc1871, nc1872, nc1873, nc1874, nc1875, nc1876, nc1877, nc1878, nc1879, nc1880, nc1881, nc1882, nc1883, nc1884, nc1885, nc1886, nc1887, nc1888, nc1889, nc1890, d[0]}),
		.dib(),
		.dipa(),
		.dipb(),
		.cea(net_89),
		.ceb(gnd_net),
		.regcea(vcc_net),
		.regceb(),
		.regsra(rstn),
		.regsrb(),
		.wea({we, we, we, we}),
		.web(),
		.eccoutdberr(),
		.eccoutsberr(),
		.eccreadaddr(),
		.eccindberr(gnd_net),
		.eccinsberr(gnd_net)
	);EMB18K #(
		.clka_inv (1'b0),
		.clkb_inv (1'b0),
		.eccreaden (1'b0),
		.eccwriteen (1'b0),
		.emb5k_1_init_file (""),
		.emb5k_2_init_file (""),
		.emb5k_3_init_file (""),
		.emb5k_4_init_file (""),
		.extension_mode ("power"),
		.init_file ("none"),
		.outreg_a (1'b0),
		.outreg_b (1'b0),
		.rammode ("sp"),
		.use_parity (1'b0),
		.width_a (1),
		.width_b (1),
		.writemode_a ("no_change"),
		.writemode_b ("write_first")
	)
	emb_60(
		.doa({nc1891, nc1892, nc1893, nc1894, nc1895, nc1896, nc1897, nc1898, nc1899, nc1900, nc1901, nc1902, nc1903, nc1904, nc1905, nc1906, nc1907, nc1908, nc1909, nc1910, nc1911, nc1912, nc1913, nc1914, nc1915, nc1916, nc1917, nc1918, nc1919, nc1920, nc1921, nc1922, nc1923, nc1924, nc1925, nc1926, nc1927, nc1928, nc1929, nc1930, nc1931, nc1932, nc1933, nc1934, nc1935, nc1936, nc1937, nc1938, nc1939, nc1940, nc1941, nc1942, nc1943, nc1944, nc1945, nc1946, nc1947, nc1948, nc1949, nc1950, nc1951, nc1952, nc1953, net_92}),
		.dob(),
		.dopa(),
		.dopb(),
		.addra({a[13], a[12], a[11], a[10], a[9], a[8], a[7], a[6], a[5], a[4], a[3], a[2], a[1], a[0]}),
		.addrb(),
		.clka(clk),
		.clkb(),
		.dia({nc1954, nc1955, nc1956, nc1957, nc1958, nc1959, nc1960, nc1961, nc1962, nc1963, nc1964, nc1965, nc1966, nc1967, nc1968, nc1969, nc1970, nc1971, nc1972, nc1973, nc1974, nc1975, nc1976, nc1977, nc1978, nc1979, nc1980, nc1981, nc1982, nc1983, nc1984, nc1985, nc1986, nc1987, nc1988, nc1989, nc1990, nc1991, nc1992, nc1993, nc1994, nc1995, nc1996, nc1997, nc1998, nc1999, nc2000, nc2001, nc2002, nc2003, nc2004, nc2005, nc2006, nc2007, nc2008, nc2009, nc2010, nc2011, nc2012, nc2013, nc2014, nc2015, nc2016, d[0]}),
		.dib(),
		.dipa(),
		.dipb(),
		.cea(net_91),
		.ceb(gnd_net),
		.regcea(vcc_net),
		.regceb(),
		.regsra(rstn),
		.regsrb(),
		.wea({we, we, we, we}),
		.web(),
		.eccoutdberr(),
		.eccoutsberr(),
		.eccreadaddr(),
		.eccindberr(gnd_net),
		.eccinsberr(gnd_net)
	);NMS_MUX u50(
		.sel(addra_pipe_14_net),
		.i0(net_90),
		.i1(net_92),
		.o(net_93)
	);NMS_AND u51(
		.i0(net_95),
		.i1(net_94),
		.o(net_89)
	);NMS_AND u52(
		.i0(net_95),
		.i1(a[14]),
		.o(net_91)
	);NMS_NOT u53(
		.i(a[14]),
		.o(net_94)
	);NMS_MUX u54(
		.sel(addra_pipe_15_net),
		.i0(net_86),
		.i1(net_93),
		.o(net_96)
	);NMS_AND u55(
		.i0(net_98),
		.i1(net_97),
		.o(net_88)
	);NMS_AND u56(
		.i0(net_98),
		.i1(a[15]),
		.o(net_95)
	);NMS_NOT u57(
		.i(a[15]),
		.o(net_97)
	);NMS_MUX u58(
		.sel(addra_pipe_16_net),
		.i0(net_79),
		.i1(net_96),
		.o(net_99)
	);NMS_AND u59(
		.i0(net_101),
		.i1(net_100),
		.o(net_81)
	);NMS_AND u60(
		.i0(net_101),
		.i1(a[16]),
		.o(net_98)
	);NMS_NOT u61(
		.i(a[16]),
		.o(net_100)
	);NMS_ADDR_PIPE_A u_addra_pipe_17(
		.clk(clk),
		.ena(net_103),
		.i(a[17]),
		.o(addra_pipe_17_net)
	);NMS_NOT u62(
		.i(we),
		.o(net_102)
	);NMS_AND u63(
		.i0(ce),
		.i1(net_102),
		.o(net_103)
	);NMS_MUX u64(
		.sel(addra_pipe_17_net),
		.i0(net_62),
		.i1(net_99),
		.o(q[0])
	);NMS_AND u65(
		.i0(ce),
		.i1(net_106),
		.o(net_64)
	);NMS_AND u66(
		.i0(ce),
		.i1(a[17]),
		.o(net_101)
	);NMS_NOT u67(
		.i(a[17]),
		.o(net_106)
	);
endmodule
module NMS_MUX (sel, i0, i1, o);
input sel;
input i0;
input i1;
output o;



assign o = sel? i1 : i0;

endmodule
module NMS_NOT (i, o);
input i;
output o;



assign o = ~i;

endmodule
module NMS_AND (i0, i1, o);
input i0;
input i1;
output o;



assign o = i0 & i1;

endmodule
module NMS_ADDR_PIPE_A (clk, ena, i, o);
input clk;
input ena;
input i;
output o;



reg r0;
always @(posedge clk) begin
	if (ena) r0 <= i;
end
assign o = r0;

endmodule


// ============================================================
//                  emb Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : P1P060N0V324C7
// Module          : NMS
// IP core         : emb
// IP Version      : 1

// AddrUsedA       : 18
// ByteWriteEn     : false
// DataUsedA       : 1
// DataUsedB       : 1
// EmbResource     : AUTO
// EmbType         : sp
// ErrorInjectMode : None
// InitFile        : 
// RegoutA         : false
// RegoutB         : false
// RegoutEnA       : false
// RegoutEnB       : false
// Simulation Files: 
// SplitEmb        : false
// SplitInfo       : 1,262144;block_0:1,4096,0,0,0;block_1:1,4096,0,4096,0;block_2:1,4096,0,8192,0;block_3:1,4096,0,12288,0;block_4:1,4096,0,16384,0;block_5:1,4096,0,20480,0;block_6:1,4096,0,24576,0;block_7:1,4096,0,28672,0;block_8:1,4096,0,32768,0;block_9:1,4096,0,36864,0;block_10:1,4096,0,40960,0;block_11:1,4096,0,45056,0;block_12:1,4096,0,49152,0;block_13:1,4096,0,53248,0;block_14:1,4096,0,57344,0;block_15:1,4096,0,61440,0;block_16:1,4096,0,65536,0;block_17:1,4096,0,69632,0;block_18:1,4096,0,73728,0;block_19:1,4096,0,77824,0;block_20:1,4096,0,81920,0;block_21:1,4096,0,86016,0;block_22:1,4096,0,90112,0;block_23:1,4096,0,94208,0;block_24:1,4096,0,98304,0;block_25:1,4096,0,102400,0;block_26:1,4096,0,106496,0;block_27:1,4096,0,110592,0;block_28:1,4096,0,114688,0;block_29:1,4096,0,118784,0;block_30:1,4096,0,122880,0;block_31:1,4096,0,126976,0;block_32:1,4096,0,131072,0;block_33:1,4096,0,135168,0;block_34:1,4096,0,139264,0;block_35:1,4096,0,143360,0;block_36:1,4096,0,147456,0;block_37:1,4096,0,151552,0;block_38:1,4096,0,155648,0;block_39:1,4096,0,159744,0;block_40:1,4096,0,163840,0;block_41:1,4096,0,167936,0;block_42:1,4096,0,172032,0;block_43:1,4096,0,176128,0;block_44:1,4096,0,180224,0;block_45:1,4096,0,184320,0;block_46:1,4096,0,188416,0;block_47:1,4096,0,192512,0;block_48:1,4096,0,196608,0;block_49:1,4096,0,200704,0;block_50:1,4096,0,204800,0;block_51:1,4096,0,208896,0;block_52:1,4096,0,212992,0;block_53:1,4096,0,217088,0;block_54:1,4096,0,221184,0;block_55:1,4096,0,225280,0;block_56:1,4096,0,229376,0;block_57:1,4096,0,233472,0;block_58:1,4096,0,237568,0;block_59:1,4096,0,241664,0;block_60:1,4096,0,245760,0;block_61:1,4096,0,249856,0;block_62:1,4096,0,253952,0;block_63:1,4096,0,258048,0
// Synthesis Files : 
// UseEccEn        : false
// WriteModeA      : No Change
// WriteModeB      : Write First
